/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tsi/security_drivers/basic/dev/68/src/rtworks/sdbasipr.h#1 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/sdbasipr.h -- generated prototypes */

#ifndef T_SD_BASIC_API
# ifndef T_OS_WIN32
# define T_SD_BASIC_API
# else
# ifndef T_STATIC_LINK
# ifndef T_SD_BASIC_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_SD_BASIC_API __declspec(dllimport)
# else
# define T_SD_BASIC_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_SD_BASIC_API __declspec(dllexport)
# else
# define T_SD_BASIC_API
# endif
# endif
# else
# define T_SD_BASIC_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* sdacl.c */
T_SD_BASIC_API T_STR T_ENTRY T_EXPORT TsdAclPermissionTypeToStr T_PROTO((
T_SD_ACL_PERMISSION_TYPE permission_type
));
T_SD_BASIC_API T_SD_ACL_PERMISSION_TYPE T_ENTRY T_EXPORT TsdAclStrToPermissionType T_PROTO((
T_STR permission_str
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclUserAdd T_PROTO((
T_SD_ACL acl,
T_STR username,
T_STR password
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclGroupAdd T_PROTO((
T_SD_ACL acl,
T_STR groupname,
T_BOOL admin
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclGroupUserAdd T_PROTO((
T_SD_ACL acl,
T_STR groupname,
T_STR username
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclPermissionAddServer T_PROTO((
T_SD_ACL acl,
T_BOOL for_a_group,
T_STR name,
T_BOOL allow,
T_STR host,
T_INT4 line
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclPermissionAddClient T_PROTO((
T_SD_ACL acl,
T_BOOL for_a_group,
T_STR name,
T_BOOL allow,
T_STR host,
T_STR project,
T_INT4 line
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclPermissionAddMembership T_PROTO((
T_SD_ACL acl,
T_BOOL for_a_group,
T_STR name,
T_BOOL allow,
T_STR host,
T_STR membership,
T_INT4 line
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclPermissionAddPublish T_PROTO((
T_SD_ACL acl,
T_BOOL for_a_group,
T_STR name,
T_BOOL allow,
T_STR host,
T_STR subject,
T_INT4 line
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclPermissionAddSubscribe T_PROTO((
T_SD_ACL acl,
T_BOOL for_a_group,
T_STR name,
T_BOOL allow,
T_STR host,
T_STR subject,
T_INT4 line
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclAuthenticatePassword T_PROTO((
T_SD_ACL acl,
T_STR username,
T_UINT1 encoded_password[20]
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclAuthorizeServer T_PROTO((
T_SD_ACL acl,
T_STR username,
T_STR host
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclAuthorizeClient T_PROTO((
T_SD_ACL acl,
T_STR username,
T_STR host,
T_STR project
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclAuthorizeMembership T_PROTO((
T_SD_ACL acl,
T_STR username,
T_STR host,
T_STR membership
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclAuthorizePublish T_PROTO((
T_SD_ACL acl,
T_STR username,
T_STR host,
T_STR subject
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclAuthorizeSubscribe T_PROTO((
T_SD_ACL acl,
T_STR username,
T_STR host,
T_STR subject
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclAuthorizeAdmin T_PROTO((
T_SD_ACL acl,
T_STR username,
T_STR host
));
T_SD_BASIC_API T_SD_ACL T_ENTRY T_EXPORT TsdAclCreate T_PROTO((void));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclDestroy T_PROTO((
T_SD_ACL * acl
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclReset T_PROTO((
T_SD_ACL acl
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclLoad T_PROTO((
T_SD_ACL acl,
T_STR location
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclDumpUsers T_PROTO((
T_SD_ACL acl,
T_OUT_FUNC out_func
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclDumpGroups T_PROTO((
T_SD_ACL acl,
T_OUT_FUNC out_func
));
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclDumpPermissions T_PROTO((
T_SD_ACL acl,
T_OUT_FUNC out_func
));

/* sdbasic.c */
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdInit T_PROTO((
T_INT4 version,
T_PTR in_value,
T_INT4 in_value_len,
T_PTR out_value,
T_INT4 * out_value_len
));

/* sdparse.c */
T_SD_BASIC_API T_BOOL T_ENTRY T_EXPORT TsdAclParseFile T_PROTO((
T_SD_ACL acl,
T_STR filename
));

#ifdef __cplusplus
}
#endif
