/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tiof/biof/dev/68/src/rtworks/connpr.h#2 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/connpr.h -- generated prototypes */

#ifndef T_CONN_API
# ifndef T_OS_WIN32
# define T_CONN_API
# else
# ifndef T_STATIC_LINK
# ifndef T_CONN_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_CONN_API __declspec(dllimport)
# else
# define T_CONN_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_CONN_API __declspec(dllexport)
# else
# define T_CONN_API
# endif
# endif
# else
# define T_CONN_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* conn.c */
T_CONN_API void T_ENTRY T_EXPORT TconnCbConnProcessGmdFailure T_PROTO((
T_CONN conn,
T_CONN_PROCESS_CB_DATA data,
T_CB_ARG dummy
));
T_CONN_API void T_ENTRY T_EXPORT TconnCbConnProcessKeepAliveCall T_PROTO((
T_CONN conn,
T_CONN_PROCESS_CB_DATA data,
T_CB_ARG output_msg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnInit T_PROTO((void));
T_CONN_API void T_ENTRY T_EXPORT TconnAddref T_PROTO((
T_CONN conn
));
T_CONN_API void T_ENTRY T_EXPORT TconnRelease T_PROTO((
T_CONN * conn
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnAcceptConnect T_PROTO((
T_CONN server_conn,
T_EDM edm,
T_STR usid,
T_CONN_CONNECT_CB_FUNC func,
T_CB_ARG arg,
T_CB * cb
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnConnect T_PROTO((
T_STR link_name,
T_EDM edm,
T_STR usid,
T_CONN_CONNECT_CB_FUNC func,
T_CB_ARG arg,
T_CB * cb
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnInitThreads T_PROTO((void));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnCreate T_PROTO((void));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetName T_PROTO((
T_CONN conn,
T_STR name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetLink T_PROTO((
T_CONN conn,
T_IPC_LINK lnk
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetSocket T_PROTO((
T_CONN conn,
T_SOCK socket_fd
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetReadSize T_PROTO((
T_CONN conn,
T_INT4 read_size
));
T_CONN_API void T_ENTRY T_EXPORT TconnSetWriteSize T_PROTO((
T_CONN conn,
T_INT4 write_size
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetBlockMode T_PROTO((
T_CONN conn,
T_BOOL block_mode
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnIoctl T_PROTO((
T_CONN conn,
T_IOCTL_COMMANDS cmd,
T_PTR arg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetTimeout T_PROTO((
T_CONN conn,
T_CONN_TIMEOUT timeout,
T_REAL8 value
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetUserProp T_PROTO((
T_CONN conn,
T_PTR user_prop
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetKeepAliveBlockMode T_PROTO((
T_CONN conn,
T_BOOL keep_alive_block_mode
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetAutoFlushSize T_PROTO((
T_CONN conn,
T_INT4 auto_flush_size
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetGmdDirName T_PROTO((
T_CONN conn,
T_STR gmd_dir_name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetGmdBaseName T_PROTO((
T_CONN conn,
T_STR gmd_base_name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetGmdMaxSize T_PROTO((
T_CONN conn,
T_UINT4 gmd_max_size
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetBlockingClose T_PROTO((
T_CONN conn,
T_BOOL block_mode
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetGmdFailureProc T_PROTO((
T_CONN conn,
T_BOOL switch_off
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetName T_PROTO((
T_CONN conn,
T_STR * name_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetLink T_PROTO((
T_CONN conn,
T_IPC_LINK * link_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetSocket T_PROTO((
T_CONN conn,
T_SOCK * socket_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetNumQueued T_PROTO((
T_CONN conn,
T_INT4 * num_queued_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetXtSource T_PROTO((
T_CONN conn,
T_SOCK * source_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetReadSize T_PROTO((
T_CONN conn,
T_INT4 * read_size_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetBlockMode T_PROTO((
T_CONN conn,
T_BOOL * block_mode_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetTimeout T_PROTO((
T_CONN conn,
T_CONN_TIMEOUT timeout,
T_REAL8 * value_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetUserProp T_PROTO((
T_CONN conn,
T_PTR * user_prop_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetKeepAliveBlockMode T_PROTO((
T_CONN conn,
T_BOOL * keep_alive_block_mode_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetAutoFlushSize T_PROTO((
T_CONN conn,
T_INT4 * auto_flush_size_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetGmdDirName T_PROTO((
T_CONN conn,
T_STR * gmd_dir_name_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetGmdBaseName T_PROTO((
T_CONN conn,
T_STR * gmd_base_name_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetGmdMaxSize T_PROTO((
T_CONN conn,
T_UINT4 * gmd_max_size_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetGmdNumPending T_PROTO((
T_CONN conn,
T_INT4 * gmd_num_pending_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetIntFormat T_PROTO((
T_CONN conn,
T_INT_FORMAT * int_format_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetRealFormat T_PROTO((
T_CONN conn,
T_REAL_FORMAT * real_format_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetCharFormat T_PROTO((
T_CONN conn,
T_CHAR_FORMAT * char_format_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetWriteSize T_PROTO((
T_CONN conn,
T_INT4 * write_size_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetUniqueSubject T_PROTO((
T_CONN conn,
T_STR * unique_subject_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetNode T_PROTO((
T_CONN conn,
T_STR * node_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetUser T_PROTO((
T_CONN conn,
T_STR * user_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetPid T_PROTO((
T_CONN conn,
T_INT4 * pid_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetArch T_PROTO((
T_CONN conn,
T_STR * arch_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGetBlockingClose T_PROTO((
T_CONN conn,
T_BOOL * block_mode_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnLock T_PROTO((
T_CONN conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnUnlock T_PROTO((
T_CONN conn
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnAccept T_PROTO((
T_CONN server_conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnReconstructMsgs T_PROTO((
T_CONN conn,
T_MSG msg_dq
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnPrint T_PROTO((
T_CONN conn,
T_OUT_FUNC out_func
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnCreateServer T_PROTO((
T_STR link_name
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnCreateClient T_PROTO((
T_STR link_name
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnConnectBegin T_PROTO((
T_STR link_name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnConnectComplete T_PROTO((
T_CONN conn,
T_REAL8 timeout
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSendInit T_PROTO((
T_CONN conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnKeepAlive T_PROTO((
T_CONN conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnCheck T_PROTO((
T_CONN conn,
T_IO_CHECK_MODE check_mode,
T_REAL8 timeout
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnRead T_PROTO((
T_CONN conn,
T_REAL8 timeout
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnFlush T_PROTO((
T_CONN conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnFlushEx T_PROTO((
T_CONN conn,
T_INT4 max_data
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgSendInternal T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgSend T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_MSG T_ENTRY T_EXPORT TconnMsgNext T_PROTO((
T_CONN conn,
T_REAL8 timeout
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgInsert T_PROTO((
T_CONN conn,
T_MSG msg,
T_INT4 pos
));
T_CONN_API T_MSG T_ENTRY T_EXPORT TconnMsgSearch T_PROTO((
T_CONN conn,
T_REAL8 timeout,
T_CONN_MSG_SEARCH_FUNC func,
T_PTR arg
));
T_CONN_API T_MSG T_ENTRY T_EXPORT TconnMsgSearchType T_PROTO((
T_CONN conn,
T_REAL8 timeout,
T_MSG_MT mt
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgProcess T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_BOOL T_ENTRY_VA T_EXPORT TconnMsgWriteVa T_PROTO((
T_CONN conn,
T_MSG_MT mt,
va_list var_arg_ptr
));
T_CONN_API T_BOOL T_ENTRY_VA T_EXPORT TconnMsgWrite T_PROTO((
T_CONN conn,
T_MSG_MT mt,
...
));
T_CONN_API T_MSG T_ENTRY T_EXPORT TconnMsgSendRpc T_PROTO((
T_CONN conn,
T_MSG call_msg,
T_REAL8 timeout
));
T_CONN_API T_MSG T_ENTRY T_EXPORT TconnMsgNextRpc T_PROTO((
T_CONN conn,
T_MSG call_msg,
T_REAL8 timeout
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnDestroy T_PROTO((
T_CONN conn
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnCreateServerLocal T_PROTO((
T_STR file_name
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnCreateClientLocal T_PROTO((
T_STR file_name
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnCreateServerTcp T_PROTO((
T_INT4 port
));
T_CONN_API T_CONN T_ENTRY T_EXPORT TconnCreateClientTcp T_PROTO((
T_STR node_name,
T_INT4 port
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMainLoop T_PROTO((
T_CONN conn,
T_REAL8 timeout
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgAck T_PROTO((
T_MSG msg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgDestroy T_PROTO((
T_MSG msg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgFilterCreate T_PROTO((
T_CONN conn,
T_INT4 mt_num,
T_CONN_MSG_FILTER_FUNC func,
T_PTR arg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnMsgFilterDestroy T_PROTO((
T_CONN conn,
T_INT4 mt_num
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetMsgsRecv T_PROTO((
T_CONN conn,
T_INT4 * msgs_recv_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetMsgsSent T_PROTO((
T_CONN conn,
T_INT4 * msgs_sent_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetBytesRecv T_PROTO((
T_CONN conn,
T_INT4 * bytes_recv_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetBytesSent T_PROTO((
T_CONN conn,
T_INT4 * bytes_sent_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetMsgsRecv8 T_PROTO((
T_CONN conn,
T_INT8 * msgs_recv_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetMsgsSent8 T_PROTO((
T_CONN conn,
T_INT8 * msgs_sent_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetBytesRecv8 T_PROTO((
T_CONN conn,
T_INT8 * bytes_recv_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnTrafficGetBytesSent8 T_PROTO((
T_CONN conn,
T_INT8 * bytes_sent_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnBufferGetReadSize T_PROTO((
T_CONN conn,
T_INT4 * read_size_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnBufferGetWriteSize T_PROTO((
T_CONN conn,
T_INT4 * write_size_return
));

/* conngmd.c */
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGmdFileCreate T_PROTO((
T_CONN conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGmdMsgResend T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGmdResend T_PROTO((
T_CONN conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGmdMsgDelete T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGmdFailure T_PROTO((
T_CONN conn,
T_INT4 seq_num,
T_STR failed_proc_name,
T_INT4 err_num
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGmdCheck T_PROTO((
T_CONN conn,
T_REAL8 wall_time
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnGmdFileDelete T_PROTO((
T_CONN conn
));

/* conncb.c */
T_CONN_API T_CB T_ENTRY T_EXPORT TconnErrorCbCreate T_PROTO((
T_CONN conn,
T_CONN_ERROR_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnErrorCbCall T_PROTO((
T_CONN conn
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnErrorCbLookup T_PROTO((
T_CONN conn,
T_CONN_ERROR_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnConnectCbCreate T_PROTO((
T_CONN conn,
T_CONN_CONNECT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnConnectCbCall T_PROTO((
T_CONN conn,
T_BOOL status,
T_INT4 err_num
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnConnectCbLookup T_PROTO((
T_CONN conn,
T_CONN_CONNECT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnAcceptCbCreate T_PROTO((
T_CONN conn,
T_CONN_ACCEPT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnAcceptCbCall T_PROTO((
T_CONN conn,
T_CONN client
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnAcceptCbLookup T_PROTO((
T_CONN conn,
T_CONN_ACCEPT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnReadCbCreate T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_READ_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnReadCbCall T_PROTO((
T_CONN conn,
T_MSG msg,
T_INT4 packet_size
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnReadCbLookup T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_READ_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnEncryptCbCreate T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_ENCRYPT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnEncryptCbCall T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnEncryptCbLookup T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_ENCRYPT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnDecryptCbCreate T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_DECRYPT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnDecryptCbCall T_PROTO((
T_CONN conn,
T_MSG msg,
T_INT4 packet_size
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnDecryptCbLookup T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_DECRYPT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnWriteCbCreate T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_WRITE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnWriteCbCall T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnWriteCbLookup T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_WRITE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnQueueCbCreate T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_QUEUE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnQueueCbCall T_PROTO((
T_CONN conn,
T_MSG msg,
T_BOOL insert_flag,
T_INT4 position
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnQueueCbLookup T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_QUEUE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnWriteBufferChangeCbCreate T_PROTO((
T_CONN conn,
T_CONN_WRITE_BUFFER_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnWriteBufferChangeCbCall T_PROTO((
T_CONN conn,
T_MSG msg,
T_BOOL write_flag
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnWriteBufferChangeCbLookup T_PROTO((
T_CONN conn,
T_CONN_WRITE_BUFFER_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnEncodeCbCreate T_PROTO((
T_CONN conn,
T_CONN_ENCODE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnEncodeCbCall T_PROTO((
T_CONN conn,
T_PTR in_packet,
T_INT4 in_packet_size,
T_PTR * out_data_return,
T_INT4 * out_data_size_return,
T_MSG msg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnEncodeCbLookup T_PROTO((
T_CONN conn,
T_CONN_ENCODE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnDecodeCbCreate T_PROTO((
T_CONN conn,
T_CONN_DECODE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnDecodeCbCall T_PROTO((
T_CONN conn,
T_PTR in_packet,
T_INT4 in_packet_size,
T_PTR * out_packet_return,
T_INT4 * out_packet_size_return
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnDecodeCbLookup T_PROTO((
T_CONN conn,
T_CONN_DECODE_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnDefaultCbCreate T_PROTO((
T_CONN conn,
T_CONN_DEFAULT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnDefaultCbLookup T_PROTO((
T_CONN conn,
T_CONN_DEFAULT_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnProcessCbCreate T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_PROCESS_CB_FUNC func,
T_CB_ARG arg
));
T_CONN_API void T_ENTRY T_EXPORT TconnProcDefCbCall T_PROTO((
T_CONN conn,
T_MSG msg
));
T_CONN_API T_CB T_ENTRY T_EXPORT TconnProcessCbLookup T_PROTO((
T_CONN conn,
T_MSG_MT mt,
T_CONN_PROCESS_CB_FUNC func,
T_CB_ARG arg
));

/* connspl.c */
T_CONN_API T_STR T_ENTRY T_EXPORT TconnGetGmdDirInternal T_PROTO((
T_CONN conn,
T_STR * stat_dir_name_return,
T_BOOL create_dirs
));
T_CONN_API T_STR T_ENTRY T_EXPORT TconnGetGmdDir T_PROTO((
T_CONN conn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSetGmdFileProt T_PROTO((
T_STR gmd_file_name,
T_INT4 gmd_dir_mode
));
T_CONN_API T_CONN_SPOOL T_ENTRY T_EXPORT TconnSpoolCreate T_PROTO((
T_CONN conn,
T_STR name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolSetMaxSize T_PROTO((
T_CONN_SPOOL spool,
T_INT4 max_size
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolGetName T_PROTO((
T_CONN_SPOOL spool,
T_STR * name_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolGetNumMsgs T_PROTO((
T_CONN_SPOOL spool,
T_INT4 * num_msgs_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolGetMaxSize T_PROTO((
T_CONN_SPOOL spool,
T_INT4 * max_size_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolFileLookup T_PROTO((
T_CONN conn,
T_STR name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolFileDelete T_PROTO((
T_CONN conn,
T_STR name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolMsgInsert T_PROTO((
T_CONN_SPOOL spool,
T_MSG msg
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolMsgRead T_PROTO((
T_CONN_SPOOL spool,
T_INT4 seq_num,
T_MSG * msg_return,
T_REAL8 * send_time_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolMsgReadByPos T_PROTO((
T_CONN_SPOOL spool,
T_INT4 msg_pos,
T_MSG * msg_return,
T_REAL8 * send_time_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolMsgDelete T_PROTO((
T_CONN_SPOOL spool,
T_INT4 seq_num
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolMsgReadSort T_PROTO((
T_CONN_SPOOL spool,
T_MSG ** msg_array_return,
T_INT4 * array_size_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolPrint T_PROTO((
T_CONN_SPOOL spool,
T_OUT_FUNC out_func
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnSpoolDestroy T_PROTO((
T_CONN_SPOOL spool
));

/* connhsn.c */
T_CONN_API T_CONN_HSN T_ENTRY T_EXPORT TconnHsnCreate T_PROTO((
T_CONN conn,
T_STR name,
T_REAL8 expiry_timeout
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnFileDelete T_PROTO((
T_CONN conn,
T_STR name
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnGetEntry T_PROTO((
T_CONN_HSN hsn,
T_CONN_ACK conn_ack,
T_CONN_HSN_ENTRY * entry
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnEntryUpdateHsn T_PROTO((
T_CONN_HSN_ENTRY entry,
T_CONN_ACK conn_ack
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnEntryUpdateLmt T_PROTO((
T_CONN_HSN_ENTRY entry,
T_CONN_ACK conn_ack
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnEntryCheckDupMsg T_PROTO((
T_CONN_HSN_ENTRY entry,
T_CONN_ACK conn_ack,
T_BOOL * duplicate
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnCheckExpired T_PROTO((
T_CONN_HSN hsn
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnPrint T_PROTO((
T_CONN_HSN hsn,
T_OUT_FUNC out_func
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnGetName T_PROTO((
T_CONN_HSN hsn,
T_STR * name_return
));
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnHsnDestroy T_PROTO((
T_CONN_HSN hsn
));

/* connlog.c */
T_CONN_API T_BOOL T_ENTRY T_EXPORT TconnLogInitThreads T_PROTO((void));
T_CONN_API void T_ENTRY T_EXPORT TconnLogInStart T_PROTO((
T_CONN conn,
T_STR fname,
T_MSG_MT mt
));
T_CONN_API void T_ENTRY T_EXPORT TconnLogOutStart T_PROTO((
T_CONN conn,
T_STR fname,
T_MSG_MT mt
));
T_CONN_API void T_ENTRY T_EXPORT TconnLogInStop T_PROTO((
T_CONN conn,
T_STR fname,
T_MSG_MT mt
));
T_CONN_API void T_ENTRY T_EXPORT TconnLogOutStop T_PROTO((
T_CONN conn,
T_STR fname,
T_MSG_MT mt
));

#ifdef __cplusplus
}
#endif
