/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tiof/biof/dev/68/src/rtworks/edmpr.h#1 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/edmpr.h -- generated prototypes */

#ifndef T_EDM_API
# ifndef T_OS_WIN32
# define T_EDM_API
# else
# ifndef T_STATIC_LINK
# ifndef T_EDM_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_EDM_API __declspec(dllimport)
# else
# define T_EDM_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_EDM_API __declspec(dllexport)
# else
# define T_EDM_API
# endif
# endif
# else
# define T_EDM_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* edm.c */
T_EDM_API T_EDM T_ENTRY T_EXPORT TedmCreate T_PROTO((
T_STR name
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmLock T_PROTO((
T_EDM edm
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmUnlock T_PROTO((
T_EDM edm
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmGetName T_PROTO((
T_EDM edm,
T_STR * name
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmGetStats T_PROTO((
T_EDM edm,
T_EDM_STATS stats
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmSetUserProp T_PROTO((
T_EDM edm,
T_PTR user_prop
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmGetUserProp T_PROTO((
T_EDM edm,
T_PTR * user_prop_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectAddInternal T_PROTO((
T_EDM edm,
T_EDM_OBJECT object
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmObjectAdd T_PROTO((
T_EDM edm,
T_EDM_OBJECT_TYPE type,
T_PTR thing,
T_IPC_LINK_MULTIPLEX_MODE multi_mode,
T_PTR multi_resource,
T_IPC_LINK_SET_MULTIPLEX_FUNC set_multiplex_func,
T_PTR set_multiplex_arg,
T_IO_CHECK_MODE check_mode,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmObjectLookupInternal T_PROTO((
T_EDM edm,
T_EDM_OBJECT_TYPE type,
T_PTR thing,
T_IPC_LINK_MULTIPLEX_MODE multi_mode,
T_IO_CHECK_MODE check_mode,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmObjectLookup T_PROTO((
T_EDM edm,
T_EDM_OBJECT_TYPE type,
T_PTR thing,
T_IPC_LINK_MULTIPLEX_MODE multi_mode,
T_IO_CHECK_MODE check_mode,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectMigrate T_PROTO((
T_EDM edm,
T_EDM_OBJECT object,
T_EDM to_edm
));
T_EDM_API T_PTR T_ENTRY T_EXPORT TedmObjectTraverse T_PROTO((
T_EDM edm,
T_EDM_OBJECT_TRAV_FUNC func,
T_PTR arg
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectRemoveInternal T_PROTO((
T_EDM edm,
T_EDM_OBJECT object,
T_BOOL flg_force_deque,
T_BOOL * flg_posted
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectRemoveInternal2 T_PROTO((
T_EDM edm,
T_EDM_OBJECT object
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectRemove T_PROTO((
T_EDM edm,
T_EDM_OBJECT object
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmPrint T_PROTO((
T_EDM edm,
T_OUT_FUNC out_func
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmDestroy T_PROTO((
T_EDM edm
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmLinkAdd T_PROTO((
T_EDM edm,
T_IPC_LINK lnk,
T_IO_CHECK_MODE check_mode,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmSourceAdd T_PROTO((
T_EDM edm,
T_PTR source,
T_IPC_LINK_MULTIPLEX_MODE multi_mode,
T_IPC_LINK_SET_MULTIPLEX_FUNC set_multiplex_func,
T_PTR set_multiplex_arg,
T_IO_CHECK_MODE check_mode,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmTimeoutAdd T_PROTO((
T_EDM edm,
T_REAL8 interval,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmEventAdd T_PROTO((
T_EDM edm,
T_PTR data,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmLinkLookup T_PROTO((
T_EDM edm,
T_IPC_LINK lnk,
T_IO_CHECK_MODE check_mode
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmSourceLookup T_PROTO((
T_EDM edm,
T_PTR source,
T_IPC_LINK_MULTIPLEX_MODE multi_mode,
T_IO_CHECK_MODE check_mode
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmTimeoutLookup T_PROTO((
T_EDM edm,
T_EDM_TIMEOUT timeout
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmEventLookup T_PROTO((
T_EDM edm,
T_EDM_EVENT event
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmInit T_PROTO((void));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmInitThreads T_PROTO((void));

/* edmobj.c */
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmObjectCreate T_PROTO((
T_EDM edm,
T_EDM_OBJECT_TYPE type,
T_PTR thing,
T_IPC_LINK_MULTIPLEX_MODE multi_mode,
T_PTR multi_resource,
T_IPC_LINK_SET_MULTIPLEX_FUNC set_multiplex_func,
T_PTR set_multiplex_arg,
T_IO_CHECK_MODE check_mode,
T_EDM_DISPATCH_FUNC dispatch_func,
T_PTR dispatch_arg
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectSetUserProp T_PROTO((
T_EDM_OBJECT object,
T_PTR user_prop
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetType T_PROTO((
T_EDM_OBJECT object,
T_EDM_OBJECT_TYPE * type_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetMultiplexMode T_PROTO((
T_EDM_OBJECT object,
T_IPC_LINK_MULTIPLEX_MODE * multiplex_mode_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetPriority T_PROTO((
T_EDM_OBJECT object,
T_INT4 * priority_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectSetPriority T_PROTO((
T_EDM_OBJECT object,
T_INT4 priority
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetObject T_PROTO((
T_EDM_OBJECT object,
T_PTR * object_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetObjectSource T_PROTO((
T_EDM_OBJECT object,
T_PTR * source_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetCheckMode T_PROTO((
T_EDM_OBJECT object,
T_IO_CHECK_MODE * check_mode_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetEDM T_PROTO((
T_EDM_OBJECT object,
T_EDM * edm_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectGetUserProp T_PROTO((
T_EDM_OBJECT object,
T_PTR * user_prop_return
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectCallSetMultiplexFunc T_PROTO((
T_EDM_OBJECT object,
T_IO_CHECK_MODE check_mode,
T_PTR multiplex_data,
T_BOOL start_flag,
T_PTR arg
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectPrint T_PROTO((
T_EDM_OBJECT object,
T_OUT_FUNC out_func
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmObjectDestroy T_PROTO((
T_EDM_OBJECT object
));

/* edmsrvc.c */
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmQueueReadyObject T_PROTO((
T_EDM_OBJECT object
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmDequeueReadyObject T_PROTO((
T_EDM_OBJECT object
));
T_EDM_API void T_ENTRY T_EXPORT TedmUpdateLastDispatch T_PROTO((
T_REAL8 wall_time,
T_EDM_OBJECT object
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmDispatch T_PROTO((
T_EDM edm,
T_REAL8 timeout
));
T_EDM_API T_EDM_OBJECT T_ENTRY T_EXPORT TedmObjectNext T_PROTO((
T_EDM edm,
T_REAL8 timeout
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmMainLoop T_PROTO((
T_EDM edm,
T_REAL8 timeout
));

/* edmto.c */
T_EDM_API T_EDM_TIMEOUT T_ENTRY T_EXPORT TedmTimeoutCreate T_PROTO((
T_REAL8 interval
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmTimeoutGetInterval T_PROTO((
T_EDM_TIMEOUT timeout,
T_REAL8 * interval
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmTimeoutDestroy T_PROTO((
T_EDM_TIMEOUT timeout
));

/* edmev.c */
T_EDM_API T_EDM_EVENT T_ENTRY T_EXPORT TedmEventCreate T_PROTO((
T_PTR data
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmEventGetData T_PROTO((
T_EDM_EVENT event,
T_PTR * data
));
T_EDM_API T_BOOL T_ENTRY T_EXPORT TedmEventDestroy T_PROTO((
T_EDM_EVENT event
));

#ifdef __cplusplus
}
#endif
