/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tpsi/cpsi/dev/68/src/rtworks/ipcmpr.h#1 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/ipcmpr.h -- generated prototypes */

#ifndef T_MULT_API
# ifndef T_OS_WIN32
# define T_MULT_API
# else
# ifndef T_STATIC_LINK
# ifndef T_MULT_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_MULT_API __declspec(dllimport)
# else
# define T_MULT_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_MULT_API __declspec(dllexport)
# else
# define T_MULT_API
# endif
# endif
# else
# define T_MULT_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* ipcmult.c */
T_MULT_API T_IPC_MRC T_ENTRY T_EXPORT TipcSrvMultCreate T_PROTO((
T_IPC_PROPERTIES props
));
T_MULT_API T_BOOL T_ENTRY T_EXPORT TipcSrvMultSetActive T_PROTO((
T_IPC_MRC mrc
));
T_MULT_API T_BOOL T_ENTRY T_EXPORT TipcSrvMultGetActive T_PROTO((
T_IPC_MRC * mrc
));
T_MULT_API T_BOOL T_ENTRY T_EXPORT TipcSrvMultMainLoop T_PROTO((
T_REAL8 timeout
));

#ifdef __cplusplus
}
#endif
