/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tkrnl/dev/68/src/rtworks/msgpr.h#2 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/msgpr.h -- generated prototypes */

#ifndef T_MSG_API
# ifndef T_OS_WIN32
# define T_MSG_API
# else
# ifndef T_STATIC_LINK
# ifndef T_MSG_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_MSG_API __declspec(dllimport)
# else
# define T_MSG_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_MSG_API __declspec(dllexport)
# else
# define T_MSG_API
# endif
# endif
# else
# define T_MSG_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* msg.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgInitThreads T_PROTO((void));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgAllocInternal T_PROTO((
T_INT4 mt_num,
T_INT4 field_size,
T_INT4 variable_size,
T_INT4 header_ext_size
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgAllocInternalEx T_PROTO((
T_INT4 mt_num,
T_INT4 field_size,
T_INT4 variable_size,
T_INT4 header_ext_size,
T_BOOL error_tolerant
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgCreate T_PROTO((
T_MSG_MT mt
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgClone T_PROTO((
T_MSG msg
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgCloneEx T_PROTO((
T_MSG msg,
T_BOOL error_tolerant
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgProtectRefCount T_PROTO((
T_MSG msg,
T_BOOL flg_protect
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgIncrRefCount T_PROTO((
T_MSG msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetRefCount T_PROTO((
T_MSG msg,
T_INT2 * ref_count_return
));
T_MSG_API T_BOOL T_ENTRY_VA T_EXPORT TmsgReadVa T_PROTO((
T_MSG msg,
va_list var_arg_list
));
T_MSG_API T_BOOL T_ENTRY_VA T_EXPORT TmsgRead T_PROTO((
T_MSG msg,
...
));
T_MSG_API T_BOOL T_ENTRY_VA T_EXPORT TmsgWriteVa T_PROTO((
T_MSG msg,
va_list var_arg_list
));
T_MSG_API T_BOOL T_ENTRY_VA T_EXPORT TmsgWrite T_PROTO((
T_MSG msg,
...
));
T_MSG_API T_PTR T_ENTRY T_EXPORT TmsgTraverse T_PROTO((
T_MSG msg,
T_MSG_TRAV_FUNC trav_func,
T_PTR arg
));
T_MSG_API void T_ENTRY T_EXPORT TmsgExpand T_PROTO((
T_MSG msg,
T_INT4 bytes_to_add
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgDestroyFragRangeInternal T_PROTO((
T_MSG msg,
T_INT4 first_field_index,
T_INT4 limit
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgDestroy T_PROTO((
T_MSG msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUncompress T_PROTO((
T_MSG msg
));

/* msgbuf.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgBufPacketSwap T_PROTO((
T_MSG_BUF buf,
T_INT_FORMAT current_int_format,
T_REAL_FORMAT current_real_format,
T_CHAR_FORMAT current_char_format,
T_INT_FORMAT dest_int_format,
T_REAL_FORMAT dest_real_format,
T_CHAR_FORMAT dest_char_format
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgBufMsgSerializeEx T_PROTO((
T_MSG_BUF buf,
T_MSG msg,
T_MSG_NAME_NUM_MAP map,
T_INT2 decoder_version,
T_PTR * ptr_return,
T_INT4 * size_return
));
T_MSG_API T_INT4 T_ENTRY T_EXPORT TmsgBufMsgSerializeEx2 T_PROTO((
T_MSG_BUF buf,
T_MSG msg,
T_MSG_NAME_NUM_MAP map,
T_INT2 decoder_version,
T_PTR * ptr_return,
T_INT4 * size_return,
T_BOOL error_tolerant
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgBufMsgSerialize T_PROTO((
T_MSG_BUF buf,
T_MSG msg
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgBufMsgDeserializeEx T_PROTO((
T_MSG_BUF buf,
T_BOOL read_only_flag,
T_MSG_NAME_NUM_MAP map,
T_INT2 encoder_version,
T_BOOL outgoing_flag
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgBufMsgDeserializeEx2 T_PROTO((
T_MSG_BUF buf,
T_BOOL read_only_flag,
T_MSG_NAME_NUM_MAP map,
T_INT2 encoder_version,
T_BOOL outgoing_flag,
T_BOOL error_tolerant
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgBufMsgDeserialize T_PROTO((
T_MSG_BUF buf
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgBufPacketToMsg T_PROTO((
T_MSG_BUF buf,
T_MSG * msg_return,
T_BOOL read_only_flag,
T_MSG_NAME_NUM_MAP map,
T_INT2 encoder_version,
T_BOOL outgoing_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetFootprint T_PROTO((
T_MSG msg,
T_UINT4 *footprint_return
));

/* msgcrypt.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSwapHeaderExt T_PROTO((
T_MSG msg,
T_MSG decrypt_msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgCheckIfEncryptionRequired T_PROTO((
T_MSG msg,
T_MSG_MT_ENCRYPT_INFO * encrypt_info_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgCheckIfDecryptionRequired T_PROTO((
T_MSG msg,
T_MSG_MT_ENCRYPT_INFO * encrypt_info_return
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgEncrypt T_PROTO((
T_MSG msg
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgDecrypt T_PROTO((
T_MSG msg
));

/* msgdata.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetDataMax T_PROTO((
T_MSG msg,
T_INT4 data_max
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetCurrent T_PROTO((
T_MSG msg,
T_INT4 field_num
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetFieldSize T_PROTO((
T_MSG_FIELD field,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendUnknown T_PROTO((
T_MSG msg,
T_MSG_FT field_type
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendChar T_PROTO((
T_MSG msg,
T_INT4 char_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt2 T_PROTO((
T_MSG msg,
T_INT4 int2
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt2Array T_PROTO((
T_MSG msg,
T_INT2 * int2_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt2ArrayPtr T_PROTO((
T_MSG msg,
T_INT2 * int2_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt4 T_PROTO((
T_MSG msg,
T_INT4 int4_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt4Array T_PROTO((
T_MSG msg,
T_INT4 * int4_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt4ArrayPtr T_PROTO((
T_MSG msg,
T_INT4 * int4_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt8 T_PROTO((
T_MSG msg,
T_INT8 int8_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt8Array T_PROTO((
T_MSG msg,
T_INT8 * int8_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendInt8ArrayPtr T_PROTO((
T_MSG msg,
T_INT8 * int8_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal4 T_PROTO((
T_MSG msg,
T_REAL8 real4
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal4Array T_PROTO((
T_MSG msg,
T_REAL4 * real4_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal4ArrayPtr T_PROTO((
T_MSG msg,
T_REAL4 * real4_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal8 T_PROTO((
T_MSG msg,
T_REAL8 real8_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal8Array T_PROTO((
T_MSG msg,
T_REAL8 * real8_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal8ArrayPtr T_PROTO((
T_MSG msg,
T_REAL8 * real8_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal16 T_PROTO((
T_MSG msg,
T_REAL16 real16_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal16Array T_PROTO((
T_MSG msg,
T_REAL16 * real16_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendReal16ArrayPtr T_PROTO((
T_MSG msg,
T_REAL16 * real16_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendStr T_PROTO((
T_MSG msg,
T_STR str_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendStrPtr T_PROTO((
T_MSG msg,
T_STR str_data,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendStrArray T_PROTO((
T_MSG msg,
T_STR * str_array_data,
T_INT4 str_array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendStrArrayPtr T_PROTO((
T_MSG msg,
T_STR * str_array_data,
T_INT4 str_array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendMsg T_PROTO((
T_MSG msg,
T_MSG msg_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendMsgPtr T_PROTO((
T_MSG msg,
T_MSG msg_data,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendMsgArray T_PROTO((
T_MSG msg,
T_MSG * msg_array_data,
T_INT4 msg_array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendMsgArrayPtr T_PROTO((
T_MSG msg,
T_MSG * msg_array_data,
T_INT4 msg_array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendGuid T_PROTO((
T_MSG msg,
T_GUID guid_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendGuidArray T_PROTO((
T_MSG msg,
T_GUID * guid_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendGuidArrayPtr T_PROTO((
T_MSG msg,
T_GUID * guid_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendBinary T_PROTO((
T_MSG msg,
T_PTR binary_data,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendBinaryPtr T_PROTO((
T_MSG msg,
T_PTR binary_data,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendStrReal8 T_PROTO((
T_MSG msg,
T_STR str_data,
T_REAL8 real8_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendXml T_PROTO((
T_MSG msg,
T_XML xml_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendXmlPtr T_PROTO((
T_MSG msg,
T_XML xml_data,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendBool T_PROTO((
T_MSG msg,
T_BOOL bool_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendBoolArray T_PROTO((
T_MSG msg,
T_BOOL * bool_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendBoolArrayPtr T_PROTO((
T_MSG msg,
T_BOOL * bool_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendTimestamp T_PROTO((
T_MSG msg,
T_REAL8 timestamp_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendTimestampArray T_PROTO((
T_MSG msg,
T_REAL8 * timestamp_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendTimestampArrayPtr T_PROTO((
T_MSG msg,
T_REAL8 * timestamp_array,
T_INT4 array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendUtf8 T_PROTO((
T_MSG msg,
T_STR str_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendUtf8Ptr T_PROTO((
T_MSG msg,
T_STR str_data,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendUtf8Array T_PROTO((
T_MSG msg,
T_STR * str_array_data,
T_INT4 str_array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendUtf8ArrayPtr T_PROTO((
T_MSG msg,
T_STR * str_array_data,
T_INT4 str_array_size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAppendByte T_PROTO((
T_MSG msg,
T_UCHAR byte_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDataSize T_PROTO((
T_MSG msg,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDataPtr T_PROTO((
T_MSG msg,
T_PTR * data_ptr_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDataMax T_PROTO((
T_MSG msg,
T_INT4 * data_max_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCurrent T_PROTO((
T_MSG msg,
T_INT4 * field_num_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCurrentFieldKnown T_PROTO((
T_MSG msg,
T_BOOL * field_valid_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCurrentFieldType T_PROTO((
T_MSG msg,
T_MSG_FT * field_type_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCurrentFieldSize T_PROTO((
T_MSG msg,
T_INT4 * field_size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCurrentFieldIntFormat T_PROTO((
T_MSG msg,
T_INT_FORMAT * field_int_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCurrentFieldRealFormat T_PROTO((
T_MSG msg,
T_REAL_FORMAT * field_real_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCurrentFieldCharFormat T_PROTO((
T_MSG msg,
T_CHAR_FORMAT * field_char_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextUnknown T_PROTO((
T_MSG msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextChar T_PROTO((
T_MSG msg,
T_CHAR * next_char
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextCharCharFormat T_PROTO((
T_MSG msg,
T_CHAR * char_return,
T_CHAR_FORMAT char_format
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextInt2 T_PROTO((
T_MSG msg,
T_INT2 * int2
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextInt2Array T_PROTO((
T_MSG msg,
T_INT2 ** int2_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextInt4 T_PROTO((
T_MSG msg,
T_INT4 * int4_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextInt4Array T_PROTO((
T_MSG msg,
T_INT4 ** int4_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextInt8 T_PROTO((
T_MSG msg,
T_INT8 * int8_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextInt8Array T_PROTO((
T_MSG msg,
T_INT8 ** int8_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextReal4 T_PROTO((
T_MSG msg,
T_REAL4 * real4
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextReal4Array T_PROTO((
T_MSG msg,
T_REAL4 ** real4_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextReal8 T_PROTO((
T_MSG msg,
T_REAL8 * real8_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextReal8Array T_PROTO((
T_MSG msg,
T_REAL8 ** real8_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextReal16 T_PROTO((
T_MSG msg,
T_REAL16 * real16_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextReal16Array T_PROTO((
T_MSG msg,
T_REAL16 ** real16_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextStr T_PROTO((
T_MSG msg,
T_STR * str_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextStrArray T_PROTO((
T_MSG msg,
T_STR ** str_array_return,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextStrCharFormat T_PROTO((
T_MSG msg,
T_STR * str_return,
T_CHAR_FORMAT char_format
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextStrArrayCharFormat T_PROTO((
T_MSG msg,
T_STR ** str_array_return,
T_INT4 * size_return,
T_CHAR_FORMAT char_format
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextMsg T_PROTO((
T_MSG msg,
T_MSG * msg_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextMsgArray T_PROTO((
T_MSG msg,
T_MSG ** msg_array_return,
T_INT4 * array_size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextGuid T_PROTO((
T_MSG msg,
T_GUID * guid_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextGuidArray T_PROTO((
T_MSG msg,
T_GUID ** guid_array_return,
T_INT4 * array_size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextBinary T_PROTO((
T_MSG msg,
T_PTR * binary_data,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextStrReal8 T_PROTO((
T_MSG msg,
T_STR * str_return,
T_REAL8 * real8_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextXml T_PROTO((
T_MSG msg,
T_XML * xml_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextBool T_PROTO((
T_MSG msg,
T_BOOL * bool_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextBoolArray T_PROTO((
T_MSG msg,
T_BOOL ** bool_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextTimestamp T_PROTO((
T_MSG msg,
T_REAL8 * timestamp_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextTimestampArray T_PROTO((
T_MSG msg,
T_REAL8 ** timestamp_array,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextUtf8 T_PROTO((
T_MSG msg,
T_STR * str_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextUtf8Array T_PROTO((
T_MSG msg,
T_STR ** str_array_return,
T_INT4 * size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextUtf8CharFormat T_PROTO((
T_MSG msg,
T_STR * str_return,
T_CHAR_FORMAT char_format
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextUtf8ArrayCharFormat T_PROTO((
T_MSG msg,
T_STR ** str_array_return,
T_INT4 * size_return,
T_CHAR_FORMAT char_format
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextByte T_PROTO((
T_MSG msg,
T_UCHAR * next_byte
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNextType T_PROTO((
T_MSG msg,
T_MSG_FT * ft_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgDeleteCurrent T_PROTO((
T_MSG msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgDeleteField T_PROTO((
T_MSG msg,
T_INT4 field_num
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateInt2ArrayPtr T_PROTO((
T_MSG_FIELD field,
T_INT2 * int2_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateInt4ArrayPtr T_PROTO((
T_MSG_FIELD field,
T_INT4 * int4_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateInt8ArrayPtr T_PROTO((
T_MSG_FIELD field,
T_INT8 * int8_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateReal4ArrayPtr T_PROTO((
T_MSG_FIELD field,
T_REAL4 * real4_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateReal8ArrayPtr T_PROTO((
T_MSG_FIELD field,
T_REAL8 * real8_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateTimestampArrayPtr T_PROTO((
T_MSG_FIELD field,
T_REAL8 * timestamp_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateReal16ArrayPtr T_PROTO((
T_MSG_FIELD field,
T_REAL16 * real16_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateStrPtr T_PROTO((
T_MSG_FIELD field,
T_STR str_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateStrArrayPtr T_PROTO((
T_MSG_FIELD field,
T_STR * str_array_data,
T_INT4 str_array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateMsgPtr T_PROTO((
T_MSG_FIELD field,
T_MSG msg_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateMsgArrayPtr T_PROTO((
T_MSG_FIELD field,
T_MSG * msg_array_data,
T_INT4 msg_array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateGuidArrayPtr T_PROTO((
T_MSG_FIELD field,
T_GUID * guid_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateBinaryPtr T_PROTO((
T_MSG_FIELD field,
T_PTR binary_data,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateXmlPtr T_PROTO((
T_MSG_FIELD field,
T_XML xml_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateBoolArrayPtr T_PROTO((
T_MSG_FIELD field,
T_BOOL * bool_array,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateUtf8Ptr T_PROTO((
T_MSG_FIELD field,
T_STR str_data
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldUpdateUtf8ArrayPtr T_PROTO((
T_MSG_FIELD field,
T_STR * str_array_data,
T_INT4 str_array_size
));

/* msgfile.c */
T_MSG_API T_MSG_FILE T_ENTRY T_EXPORT TmsgFileCreate T_PROTO((
T_STR file_name,
T_MSG_FILE_CREATE_MODE mode
));
T_MSG_API T_MSG_FILE T_ENTRY T_EXPORT TmsgFileCreateFromFile T_PROTO((
FILE * file,
T_MSG_FILE_CREATE_MODE mode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFileRead T_PROTO((
T_MSG_FILE msg_file,
T_MSG * msg_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFileWrite T_PROTO((
T_MSG_FILE msg_file,
T_MSG msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFileDestroy T_PROTO((
T_MSG_FILE msg_file
));

/* msghdr.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetType T_PROTO((
T_MSG msg,
T_MSG_MT type
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetNumFields T_PROTO((
T_MSG msg,
T_INT4 num_fields
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetSeqNum T_PROTO((
T_MSG msg,
T_INT4 seq_num
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetSrvSeqNum T_PROTO((
T_MSG msg,
T_INT4 server_seq_num
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetPriority T_PROTO((
T_MSG msg,
T_INT4 msg_priority
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetCompression T_PROTO((
T_MSG msg,
T_BOOL compression
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetDeliveryMode T_PROTO((
T_MSG msg,
T_MSG_DELIVERY_MODE delivery_mode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetResendMode T_PROTO((
T_MSG msg,
T_BOOL resend_mode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetUserProp T_PROTO((
T_MSG msg,
T_INT4 user_prop
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetSender T_PROTO((
T_MSG msg,
T_STR sender
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetSenderServer T_PROTO((
T_MSG msg,
T_STR sender_server
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetDest T_PROTO((
T_MSG msg,
T_STR dest
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetApp T_PROTO((
T_MSG msg,
T_STR app
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetDestServer T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL dup_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetDestServerList T_PROTO((
T_MSG msg,
T_PTR_ARY dest_server_list,
T_BOOL dup_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetDestClientList T_PROTO((
T_MSG msg,
T_STR * dest_client_list,
T_INT4 num_dest_clients,
T_BOOL dup_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetScope T_PROTO((
T_MSG msg,
T_STR scope
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetScopeList T_PROTO((
T_MSG msg,
T_STR * scope_list,
T_INT4 num_scopes,
T_BOOL dup_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetDeliveryTimeout T_PROTO((
T_MSG msg,
T_REAL8 timeout
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetLbMode T_PROTO((
T_MSG msg,
T_MSG_LB_MODE lb_mode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetReadOnly T_PROTO((
T_MSG msg,
T_BOOL read_only
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetHeaderStrEncode T_PROTO((
T_MSG msg,
T_BOOL header_encode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetLocalDelivery T_PROTO((
T_MSG msg,
T_BOOL local_delivery
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetGroupSenderId T_PROTO((
T_MSG msg,
T_INT4 group_sender
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetGroupDestIdList T_PROTO((
T_MSG msg,
T_INT4 * group_dest_id_list,
T_INT4 num_group_dest_ids,
T_BOOL dup_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetCharFormat T_PROTO((
T_MSG msg,
T_CHAR_FORMAT char_format
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGenerateMessageId T_PROTO((
T_MSG msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetCorrelationId T_PROTO((
T_MSG msg,
T_STR correlation_id
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetReplyTo T_PROTO((
T_MSG msg,
T_STR subj
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetExpiration T_PROTO((
T_MSG msg,
T_REAL8 expiration
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetSenderTimestamp T_PROTO((
T_MSG msg,
T_REAL8 sender_timestamp
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetArrivalTimestamp T_PROTO((
T_MSG msg,
T_REAL8 arrival_timestamp
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetType T_PROTO((
T_MSG msg,
T_MSG_MT * type_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetTypeNum T_PROTO((
T_MSG msg,
T_INT4 * type_num_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNumFields T_PROTO((
T_MSG msg,
T_INT4 * num_fields_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNumNamedFields T_PROTO((
T_MSG msg,
T_INT4 * num_named_fields_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetSeqNum T_PROTO((
T_MSG msg,
T_INT4 * seq_num_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetSrvSeqNum T_PROTO((
T_MSG msg,
T_INT4 * server_seq_num_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetPriority T_PROTO((
T_MSG msg,
T_INT2 * priority_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCompression T_PROTO((
T_MSG msg,
T_BOOL * compression_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDeliveryMode T_PROTO((
T_MSG msg,
T_MSG_DELIVERY_MODE * delivery_mode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetResendMode T_PROTO((
T_MSG msg,
T_BOOL * resend_mode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetUserProp T_PROTO((
T_MSG msg,
T_INT4 * user_prop_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetSender T_PROTO((
T_MSG msg,
T_STR * sender_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetSenderServer T_PROTO((
T_MSG msg,
T_STR * sender_server_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDest T_PROTO((
T_MSG msg,
T_STR * dest_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetApp T_PROTO((
T_MSG msg,
T_STR * app_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDestServerList T_PROTO((
T_MSG msg,
T_PTR_ARY dest_server_list_in_out
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDestClientList T_PROTO((
T_MSG msg,
T_STR ** dest_client_list_return,
T_INT4 * num_dest_clients_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetScopeList T_PROTO((
T_MSG msg,
T_STR ** scope_list_return,
T_INT4 * num_scopes_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetDeliveryTimeout T_PROTO((
T_MSG msg,
T_REAL8 * timeout_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetLbMode T_PROTO((
T_MSG msg,
T_MSG_LB_MODE * lb_mode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetReadOnly T_PROTO((
T_MSG msg,
T_BOOL * read_only_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetHeaderStrEncode T_PROTO((
T_MSG msg,
T_BOOL * header_encode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetLocalDelivery T_PROTO((
T_MSG msg,
T_BOOL * local_delivery_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetGroupSenderId T_PROTO((
T_MSG msg,
T_INT4 * group_sender_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetGroupDestIdList T_PROTO((
T_MSG msg,
T_INT4 ** group_dest_id_list_return,
T_INT4 * num_group_dest_ids_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetIntFormat T_PROTO((
T_MSG msg,
T_INT_FORMAT * int_format_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetRealFormat T_PROTO((
T_MSG msg,
T_REAL_FORMAT * real_format_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCharFormat T_PROTO((
T_MSG msg,
T_CHAR_FORMAT * char_format_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetMessageId T_PROTO((
T_MSG msg,
T_STR * message_id_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetCorrelationId T_PROTO((
T_MSG msg,
T_STR * correlation_id_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetReplyTo T_PROTO((
T_MSG msg,
T_STR * subj_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetExpiration T_PROTO((
T_MSG msg,
T_REAL8 * expiration_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetSenderTimestamp T_PROTO((
T_MSG msg,
T_REAL8 * sender_timestamp_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetArrivalTimestamp T_PROTO((
T_MSG msg,
T_REAL8 * arrival_timestamp_return
));

/* msgmt.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtLogAddMt T_PROTO((
T_MT_LOG_TYPE log_type,
T_MSG_MT mt
));
T_MSG_API T_PTR_ARY T_ENTRY T_EXPORT TmsgMtLogDataTable T_PROTO((void));
T_MSG_API T_PTR_ARY T_ENTRY T_EXPORT TmsgMtLogStatusTable T_PROTO((void));
T_MSG_API T_PTR_ARY T_ENTRY T_EXPORT TmsgMtLogInternalTable T_PROTO((void));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtLogRemoveMt T_PROTO((
T_MT_LOG_TYPE log_type,
T_MSG_MT mt
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtLogMtCreate T_PROTO((
T_MSG_MT mt,
T_PTR_ARY * table_ptr
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtLogMtDestroy T_PROTO((
T_MSG_MT mt,
T_PTR_ARY * table_ptr
));
T_MSG_API void T_ENTRY T_EXPORT TmsgMtInitThreadSafe T_PROTO((void));
T_MSG_API T_HASH_TABLE T_ENTRY T_EXPORT TmsgMtGetNameTable T_PROTO((void));
T_MSG_API T_HASH_TABLE T_ENTRY T_EXPORT TmsgMtGetNumTable T_PROTO((void));
T_MSG_API T_MSG_MT T_ENTRY T_EXPORT TmsgMtCreate T_PROTO((
T_STR name,
T_INT4 num,
T_STR msg_file_grammar
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetCompression T_PROTO((
T_MSG_MT mt,
T_BOOL compression
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetPriority T_PROTO((
T_MSG_MT mt,
T_INT4 priority
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetPriorityUnknown T_PROTO((
T_MSG_MT mt
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetDeliveryMode T_PROTO((
T_MSG_MT mt,
T_MSG_DELIVERY_MODE delivery_mode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetLbMode T_PROTO((
T_MSG_MT mt,
T_MSG_LB_MODE lb_mode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetDeliveryTimeout T_PROTO((
T_MSG_MT mt,
T_REAL8 delivery_timeout
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetUserProp T_PROTO((
T_MSG_MT mt,
T_INT4 user_prop
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetHeaderStrEncode T_PROTO((
T_MSG_MT mt,
T_BOOL header_encode
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetLocalDelivery T_PROTO((
T_MSG_MT mt,
T_BOOL local_delivery
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetName T_PROTO((
T_MSG_MT mt,
T_STR * name_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetNum T_PROTO((
T_MSG_MT mt,
T_INT4 * num_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetCompression T_PROTO((
T_MSG_MT mt,
T_BOOL * compression_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetPriority T_PROTO((
T_MSG_MT mt,
T_INT2 * priority_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetDeliveryMode T_PROTO((
T_MSG_MT mt,
T_MSG_DELIVERY_MODE * delivery_mode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetLbMode T_PROTO((
T_MSG_MT mt,
T_MSG_LB_MODE * lb_mode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetDeliveryTimeout T_PROTO((
T_MSG_MT mt,
T_REAL8 * delivery_timeout_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetUserProp T_PROTO((
T_MSG_MT mt,
T_INT4 * user_prop_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetHeaderStrEncode T_PROTO((
T_MSG_MT mt,
T_BOOL * header_encode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetLocalDelivery T_PROTO((
T_MSG_MT mt,
T_BOOL * local_delivery_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetGrammar T_PROTO((
T_MSG_MT mt,
T_STR * grammar_return
));
T_MSG_API T_MSG_MT T_ENTRY T_EXPORT TmsgMtLookup T_PROTO((
T_STR name
));
T_MSG_API T_MSG_MT T_ENTRY T_EXPORT TmsgMtLookupByNum T_PROTO((
T_INT4 num
));
T_MSG_API T_PTR T_ENTRY T_EXPORT TmsgMtTraverse T_PROTO((
T_MSG_MT_TRAV_FUNC func,
T_PTR arg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtDestroy T_PROTO((
T_MSG_MT mt
));
T_MSG_API void T_ENTRY T_EXPORT TmsgMtEncryptKey T_PROTO((
T_ENCRYPT_KEY encrypt_key
));
T_MSG_API void T_ENTRY T_EXPORT TmsgMtDecryptKey T_PROTO((
T_ENCRYPT_KEY encrypt_key
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetKey T_PROTO((
T_MSG_MT mt,
T_ENCRYPT_KEY encrypt_key
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetEncryptInfoByNumInternal T_PROTO((
T_INT4 mt_num,
T_MSG_MT_ENCRYPT_INFO * encrypt_info_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetEncryptFunc T_PROTO((
T_MSG_MT mt,
T_MSG_ENCRYPT_FUNC encrypt_func,
T_PTR encrypt_arg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetEncryptFunc T_PROTO((
T_MSG_MT mt,
T_MSG_ENCRYPT_FUNC * encrypt_func_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtSetDecryptFunc T_PROTO((
T_MSG_MT mt,
T_MSG_DECRYPT_FUNC decrypt_func,
T_PTR decrypt_arg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtGetDecryptFunc T_PROTO((
T_MSG_MT mt,
T_MSG_DECRYPT_FUNC * decrypt_func_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgMtIsEncryptTableEmpty T_PROTO((void));

/* msgnmf.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNamesClone T_PROTO((
T_MSG source_msg,
T_MSG dest_msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNameIndex T_PROTO((
T_MSG msg,
T_INT4 index,
T_STR * result
));
T_MSG_API void T_ENTRY T_EXPORT TmsgNamesTableFill T_PROTO((
T_MSG msg,
T_STR * names_array,
T_INT4 * index_array,
T_INT4 length
));
T_MSG_API T_UINT4 T_ENTRY T_EXPORT TmsgNamesTableGetFootprint T_PROTO((
T_MSG msg
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNamesTableExtract T_PROTO((
T_MSG msg,
T_STR ** names_array_return,
T_INT4 ** index_array_return,
T_INT4 * length_return
));
T_MSG_API void T_ENTRY T_EXPORT TmsgNamesTableDestroy T_PROTO((
T_MSG msg
));
T_MSG_API void T_ENTRY T_EXPORT TmsgNamesDelete T_PROTO((
T_MSG msg,
T_INT4 num_fields
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedBinary T_PROTO((
T_MSG msg,
T_STR name,
T_PTR value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedBinaryPtr T_PROTO((
T_MSG msg,
T_STR name,
T_PTR value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedChar T_PROTO((
T_MSG msg,
T_STR name,
T_CHAR value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedGuid T_PROTO((
T_MSG msg,
T_STR name,
T_GUID value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedGuidArray T_PROTO((
T_MSG msg,
T_STR name,
T_GUID * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedGuidArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_GUID * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt2 T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt2Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt2ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt4 T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt4Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt4ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt8 T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt8Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedInt8ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedMsg T_PROTO((
T_MSG msg,
T_STR name,
T_MSG value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedMsgArray T_PROTO((
T_MSG msg,
T_STR name,
T_MSG * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedMsgArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_MSG * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedMsgPtr T_PROTO((
T_MSG msg,
T_STR name,
T_MSG value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal4 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal4Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal4ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal8 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal8Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal8ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal16 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal16Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedReal16ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedStr T_PROTO((
T_MSG msg,
T_STR name,
T_STR value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedStrArray T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedStrArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedStrPtr T_PROTO((
T_MSG msg,
T_STR name,
T_STR value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedUnknown T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 type
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedXml T_PROTO((
T_MSG msg,
T_STR name,
T_XML value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedXmlPtr T_PROTO((
T_MSG msg,
T_STR name,
T_XML value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedBool T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedBoolArray T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedBoolArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedTimestamp T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedTimestampArray T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedTimestampArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedUtf8 T_PROTO((
T_MSG msg,
T_STR name,
T_STR value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedUtf8Ptr T_PROTO((
T_MSG msg,
T_STR name,
T_STR value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedUtf8Array T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedUtf8ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgAddNamedByte T_PROTO((
T_MSG msg,
T_STR name,
T_UCHAR value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedBinary T_PROTO((
T_MSG msg,
T_STR name,
T_PTR * value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedChar T_PROTO((
T_MSG msg,
T_STR name,
T_CHAR * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedGuid T_PROTO((
T_MSG msg,
T_STR name,
T_GUID * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedGuidArray T_PROTO((
T_MSG msg,
T_STR name,
T_GUID ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedInt2 T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedInt2Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedInt4 T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedInt4Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedInt8 T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedInt8Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedMsg T_PROTO((
T_MSG msg,
T_STR name,
T_MSG * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedMsgArray T_PROTO((
T_MSG msg,
T_STR name,
T_MSG ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedReal4 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedReal4Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedReal8 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedReal8Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedReal16 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedReal16Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedStr T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedStrArray T_PROTO((
T_MSG msg,
T_STR name,
T_STR ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedUnknown T_PROTO((
T_MSG msg,
T_STR name
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedXml T_PROTO((
T_MSG msg,
T_STR name,
T_XML * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedBool T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedBoolArray T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedTimestamp T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedTimestampArray T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedUtf8 T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedUtf8Array T_PROTO((
T_MSG msg,
T_STR name,
T_STR ** value,
T_INT4 * size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedByte T_PROTO((
T_MSG msg,
T_STR name,
T_UCHAR * value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetTypeNamed T_PROTO((
T_MSG msg,
T_STR name,
T_MSG_FT * type
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNamedFieldKnown T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL * bool_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgExistsNamed T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL * bool_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgGetNameCurrent T_PROTO((
T_MSG msg,
T_STR * name_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgSetNameCurrent T_PROTO((
T_MSG msg,
T_STR name
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgDeleteNamedField T_PROTO((
T_MSG msg,
T_STR name
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFieldNameDelete T_PROTO((
T_MSG msg,
T_STR name
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNamesTableUpdate T_PROTO((
T_MSG msg,
T_INT4 field_num
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedBinary T_PROTO((
T_MSG msg,
T_STR name,
T_PTR value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedBinaryPtr T_PROTO((
T_MSG msg,
T_STR name,
T_PTR value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedChar T_PROTO((
T_MSG msg,
T_STR name,
T_CHAR value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedGuid T_PROTO((
T_MSG msg,
T_STR name,
T_GUID value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedGuidArray T_PROTO((
T_MSG msg,
T_STR name,
T_GUID * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedGuidArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_GUID * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt2 T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt2Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt2ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_INT2 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt4 T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt4Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt4ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_INT4 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt8 T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt8Array T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedInt8ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_INT8 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedMsg T_PROTO((
T_MSG msg,
T_STR name,
T_MSG value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedMsgArray T_PROTO((
T_MSG msg,
T_STR name,
T_MSG * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedMsgArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_MSG * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedMsgPtr T_PROTO((
T_MSG msg,
T_STR name,
T_MSG value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal4 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal4Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal4ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL4 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal8 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal8Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal8ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal16 T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal16Array T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedReal16ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL16 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedStr T_PROTO((
T_MSG msg,
T_STR name,
T_STR value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedStrArray T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedStrArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedStrPtr T_PROTO((
T_MSG msg,
T_STR name,
T_STR value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedXml T_PROTO((
T_MSG msg,
T_STR name,
T_XML value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedXmlPtr T_PROTO((
T_MSG msg,
T_STR name,
T_XML value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedBool T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedBoolArray T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedBoolArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_BOOL * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedTimestamp T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedTimestampArray T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedTimestampArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_REAL8 * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedUtf8 T_PROTO((
T_MSG msg,
T_STR name,
T_STR value
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedUtf8Ptr T_PROTO((
T_MSG msg,
T_STR name,
T_STR value,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedUtf8Array T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedUtf8ArrayPtr T_PROTO((
T_MSG msg,
T_STR name,
T_STR * value,
T_INT4 size,
T_MSG_FIELD * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgUpdateNamedByte T_PROTO((
T_MSG msg,
T_STR name,
T_UCHAR value
));

/* msgprop.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgPropExtSet T_PROTO((
T_MSG msg,
T_INT1 key,
T_MSG_FT ft,
T_PTR val,
T_INT4 array_size
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgPropExtSetStd T_PROTO((
T_MSG msg,
T_MSG_BUF buf,
T_MSG_NAME_NUM_MAP map,
T_INT2 decoder_version
));
T_MSG_API T_INT4 T_ENTRY T_EXPORT TmsgPropExtSetStdEx T_PROTO((
T_MSG msg,
T_MSG_BUF buf,
T_MSG_NAME_NUM_MAP map,
T_INT2 decoder_version,
T_BOOL error_tolerant
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgPropExtGet T_PROTO((
T_MSG msg,
T_INT1 key,
T_MSG_FT * ft_return,
T_PTR * val_return,
T_INT4 * array_size_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgPropExtGetBinary T_PROTO((
T_MSG msg,
T_INT1 key,
T_MSG_FIELD_STRUCT * field_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgPropExtGetStd T_PROTO((
T_MSG msg,
T_MSG_BUF buf,
T_INT4 size,
T_MSG_NAME_NUM_MAP map,
T_INT2 encoder_version,
T_BOOL outgoing_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgPropExtDelete T_PROTO((
T_MSG msg,
T_INT1 key
));

/* msgprops.c */
T_MSG_API T_PROPERTIES T_ENTRY T_EXPORT TmsgPropertiesCreateMsg T_PROTO((
T_MSG msg
));
T_MSG_API T_MSG T_ENTRY T_EXPORT TmsgPropertiesMsgCreate T_PROTO((
T_PROPERTIES props
));

/* msgtest.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgTestPrintExtProps T_PROTO((
T_MSG msg,
T_OUT_FUNC out_func
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgTestPrint T_PROTO((
T_MSG msg,
T_OUT_FUNC out_func
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgTestPrintMt T_PROTO((
T_MSG_MT mt,
T_OUT_FUNC out_func
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgTestPrintError T_PROTO((
T_MSG msg
));

/* msgutil.c */
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgFtToStr T_PROTO((
T_MSG_FT type,
T_STR * str_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgStrToFt T_PROTO((
T_STR ft_str,
T_MSG_FT * ft_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgDeliveryModeToStr T_PROTO((
T_MSG_DELIVERY_MODE delivery_mode,
T_STR * delivery_mode_str_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgStrToDeliveryMode T_PROTO((
T_STR delivery_mode_str,
T_MSG_DELIVERY_MODE * delivery_mode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgLbModeToStr T_PROTO((
T_MSG_LB_MODE lb_mode,
T_STR * lb_mode_str_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgStrToLbMode T_PROTO((
T_STR lb_mode_str,
T_MSG_LB_MODE * lb_mode_return
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNameToNum T_PROTO((
T_INT4 * num_out,
T_STR name_inout,
T_MSG_NAME_NUM_MAP map
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNumToName T_PROTO((
T_STR * name_inout,
T_INT4 num_in,
T_MSG_NAME_NUM_MAP map,
T_BOOL outgoing_flag
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNamesToNums T_PROTO((
T_INT4 * num_arr_out,
T_STR * name_arr_inout,
T_INT4 * arr_size_inout,
T_MSG_NAME_NUM_MAP map
));
T_MSG_API T_BOOL T_ENTRY T_EXPORT TmsgNumsToNames T_PROTO((
T_STR * name_arr_inout,
T_INT4 * num_arr_in,
T_INT4 arr_size,
T_MSG_NAME_NUM_MAP map,
T_BOOL outgoing_flag
));

#ifdef __cplusplus
}
#endif
