/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tiof/siof/dev/68/src/rtworks/siocpr.h#1 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/siocpr.h -- generated prototypes */

#ifndef T_SIOC_API
# ifndef T_OS_WIN32
# define T_SIOC_API
# else
# ifndef T_STATIC_LINK
# ifndef T_SIOC_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_SIOC_API __declspec(dllimport)
# else
# define T_SIOC_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_SIOC_API __declspec(dllexport)
# else
# define T_SIOC_API
# endif
# endif
# else
# define T_SIOC_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* sioc.c */
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocInit T_PROTO((void));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocInitThreads T_PROTO((void));

/* siociq.c */
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQCreate T_PROTO((
T_EDM edm,
T_PTR ioo,
T_SIOC_MSG_IQ * iq
));
T_SIOC_API void T_ENTRY T_EXPORT TsiocMsgIQAddref T_PROTO((
T_SIOC_MSG_IQ iq
));
T_SIOC_API T_INT4 T_ENTRY T_EXPORT TsiocMsgIQGetref T_PROTO((
T_SIOC_MSG_IQ iq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQGetEDM T_PROTO((
T_SIOC_MSG_IQ iq,
T_EDM * edm
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQGetIOO T_PROTO((
T_SIOC_MSG_IQ iq,
T_PTR * ioo
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQGetSize T_PROTO((
T_SIOC_MSG_IQ iq,
T_INT4 * size
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQIsEmpty T_PROTO((
T_SIOC_MSG_IQ iq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQAppend T_PROTO((
T_SIOC_MSG_IQ iq,
T_MSG msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQPush T_PROTO((
T_SIOC_MSG_IQ iq,
T_MSG msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQFirst T_PROTO((
T_SIOC_MSG_IQ iq,
T_MSG * msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQLast T_PROTO((
T_SIOC_MSG_IQ iq,
T_MSG * msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQPop T_PROTO((
T_SIOC_MSG_IQ iq,
T_MSG * msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQRemove T_PROTO((
T_SIOC_MSG_IQ iq,
T_MSG msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQMigrate T_PROTO((
T_SIOC_MSG_IQ iq1,
T_SIOC_MSG_IQ iq2
));
T_SIOC_API T_PTR T_ENTRY T_EXPORT TsiocMsgIQTraverse T_PROTO((
T_SIOC_MSG_IQ iq,
T_SIOC_MSG_IQ_TRAV_FUNC func,
T_PTR arg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQOQListAppend T_PROTO((
T_SIOC_MSG_IQ iq,
T_SIOC_MSG_OQ oq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQOQListGetSize T_PROTO((
T_SIOC_MSG_IQ iq,
T_INT4 * size
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQOQListIsEmpty T_PROTO((
T_SIOC_MSG_IQ iq
));
T_SIOC_API T_PTR T_ENTRY T_EXPORT TsiocMsgIQOQListTraverse T_PROTO((
T_SIOC_MSG_IQ iq,
T_SIOC_MSG_IQ_OQ_TRAV_FUNC func,
T_PTR arg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQOQListPop T_PROTO((
T_SIOC_MSG_IQ iq,
T_SIOC_MSG_OQ * oq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQOQListRemove T_PROTO((
T_SIOC_MSG_IQ iq,
T_SIOC_MSG_OQ oq
));
T_SIOC_API void T_ENTRY T_EXPORT TsiocMsgIQRelease T_PROTO((
T_SIOC_MSG_IQ * iq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgIQDestroy T_PROTO((
T_SIOC_MSG_IQ * iq
));

/* siocoq.c */
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQCreate T_PROTO((
T_SIOC_MSG_IQ iq,
T_PTR ioo,
T_SIOC_MSG_OQ * oq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQCreateEx T_PROTO((
T_SIOC_MSG_IQ iq,
T_PTR ioo,
T_SIOC_MSG_OQ * oq,
T_BOOL pooled
));
T_SIOC_API void T_ENTRY T_EXPORT TsiocMsgOQAddref T_PROTO((
T_SIOC_MSG_OQ oq
));
T_SIOC_API T_INT4 T_ENTRY T_EXPORT TsiocMsgOQGetref T_PROTO((
T_SIOC_MSG_OQ oq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQGetIQ T_PROTO((
T_SIOC_MSG_OQ oq,
T_SIOC_MSG_IQ * iq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQGetIOO T_PROTO((
T_SIOC_MSG_OQ oq,
T_PTR * ioo
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQGetSize T_PROTO((
T_SIOC_MSG_OQ oq,
T_INT4 * size
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQIsEmpty T_PROTO((
T_SIOC_MSG_OQ oq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQAppend T_PROTO((
T_SIOC_MSG_OQ oq,
T_MSG msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQPush T_PROTO((
T_SIOC_MSG_OQ oq,
T_MSG msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQFirst T_PROTO((
T_SIOC_MSG_OQ oq,
T_MSG * msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQLast T_PROTO((
T_SIOC_MSG_OQ oq,
T_MSG * msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQPop T_PROTO((
T_SIOC_MSG_OQ oq,
T_MSG * msg
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQMigrate T_PROTO((
T_SIOC_MSG_OQ oq1,
T_SIOC_MSG_OQ oq2
));
T_SIOC_API T_PTR T_ENTRY T_EXPORT TsiocMsgOQTraverse T_PROTO((
T_SIOC_MSG_OQ oq,
T_SIOC_MSG_OQ_TRAV_FUNC func,
T_PTR arg
));
T_SIOC_API void T_ENTRY T_EXPORT TsiocMsgOQRelease T_PROTO((
T_SIOC_MSG_OQ * oq
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocMsgOQDestroy T_PROTO((
T_SIOC_MSG_OQ * oq
));

/* siocctl.c */
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocIoctlCreate T_PROTO((
T_IOCTL_COMMANDS cmd,
T_PTR data,
T_SIOC_IOCTL * ioctl
));
T_SIOC_API void T_ENTRY T_EXPORT TsiocIoctlAddref T_PROTO((
T_SIOC_IOCTL ioctl
));
T_SIOC_API T_INT4 T_ENTRY T_EXPORT TsiocIoctlGetref T_PROTO((
T_SIOC_IOCTL ioctl
));
T_SIOC_API void T_ENTRY T_EXPORT TsiocIoctlSetError T_PROTO((
T_SIOC_IOCTL ioctl,
T_BOOL status,
T_INT4 error
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocIoctlSetUserProp T_PROTO((
T_SIOC_IOCTL ioctl,
T_PTR user_prop
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocIoctlGetUserProp T_PROTO((
T_SIOC_IOCTL ioctl,
T_PTR * user_prop
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocIoctlGetCommand T_PROTO((
T_SIOC_IOCTL ioctl,
T_IOCTL_COMMANDS * cmd
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocIoctlGetData T_PROTO((
T_SIOC_IOCTL ioctl,
T_PTR * data
));
T_SIOC_API void T_ENTRY T_EXPORT TsiocIoctlRelease T_PROTO((
T_SIOC_IOCTL * ioctl
));
T_SIOC_API T_BOOL T_ENTRY T_EXPORT TsiocIoctlDestroy T_PROTO((
T_SIOC_IOCTL * ioctl
));

#ifdef __cplusplus
}
#endif
