/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tpsi/dpsi/dev/68/src/rtworks/spsspr.h#1 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/spsspr.h -- generated prototypes */

#ifndef T_SPSS_API
# ifndef T_OS_WIN32
# define T_SPSS_API
# else
# ifndef T_STATIC_LINK
# ifndef T_SPSS_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_SPSS_API __declspec(dllimport)
# else
# define T_SPSS_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_SPSS_API __declspec(dllexport)
# else
# define T_SPSS_API
# endif
# endif
# else
# define T_SPSS_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* spss.c */
T_SPSS_API T_BOOL T_ENTRY T_EXPORT spssMsgSubjectFilter T_PROTO((
T_SPSS spss,
T_MSG msg
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssPropertiesSet T_PROTO((
T_SPSS spss,
T_STR name,
T_STR value
));
T_SPSS_API T_STR T_ENTRY T_EXPORT TspssPropertiesGet T_PROTO((
T_SPSS spss,
T_STR name
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssCreate T_PROTO((
T_EDM edm,
T_STR usid,
T_STR project,
T_STR dsp,
T_IPC_SRV_DISCONNECT_MODE dm,
T_PTR_ARY snames,
T_REAL8 rd,
T_UINT4 odmql,
T_SPSS * spss
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSetServerNames T_PROTO((
T_SPSS spss,
T_PTR_ARY snames
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSetReconnectDelay T_PROTO((
T_SPSS spss,
T_REAL8 rd
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSetOutboundDataMsgQLimit T_PROTO((
T_SPSS spss,
T_UINT4 odmql
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSetCredentials T_PROTO((
T_SPSS spss,
T_INT4 auth_policy_id,
T_PTR auth_data,
T_INT4 auth_data_len
));
T_SPSS_API T_EDM T_ENTRY T_EXPORT TspssGetEDM T_PROTO((
T_SPSS spss
));
T_SPSS_API T_STR T_ENTRY T_EXPORT TspssGetUniqueSubject T_PROTO((
T_SPSS spss
));
T_SPSS_API T_STR T_ENTRY T_EXPORT TspssGetProject T_PROTO((
T_SPSS spss
));
T_SPSS_API T_STR T_ENTRY T_EXPORT TspssGetDsp T_PROTO((
T_SPSS spss
));
T_SPSS_API T_IPC_SRV_DISCONNECT_MODE T_ENTRY T_EXPORT TspssGetDisconnectMode T_PROTO((
T_SPSS spss
));
T_SPSS_API T_SPSS_STATE T_ENTRY T_EXPORT TspssGetState T_PROTO((
T_SPSS spss
));
T_SPSS_API T_PTR_ARY T_ENTRY T_EXPORT TspssGetServerNames T_PROTO((
T_SPSS spss
));
T_SPSS_API T_STR_LIST T_ENTRY T_EXPORT TspssGetOServerNames T_PROTO((
T_SPSS spss
));
T_SPSS_API T_REAL8 T_ENTRY T_EXPORT TspssGetReconnectDelay T_PROTO((
T_SPSS spss
));
T_SPSS_API T_REAL8 T_ENTRY T_EXPORT TspssGetOutboundDataMsgQLimit T_PROTO((
T_SPSS spss
));
T_SPSS_API T_SPSS_SUBJECT T_ENTRY T_EXPORT TspssGetSubject T_PROTO((
T_SPSS spss,
T_STR name
));
T_SPSS_API T_SPSS_STAT T_ENTRY T_EXPORT TspssGetStat T_PROTO((
T_SPSS spss
));
T_SPSS_API T_PTR T_ENTRY T_EXPORT TspssGetSvc T_PROTO((
T_SPSS spss
));
T_SPSS_API void T_ENTRY T_EXPORT TspssAddref T_PROTO((
T_SPSS spss
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssPrint T_PROTO((
T_SPSS spss,
T_OUT_FUNC out_func
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssOpen T_PROTO((
T_SPSS spss
));
T_SPSS_API T_SAFE_STR_STRUCT T_ENTRY T_EXPORT TspssSubjectAppendDsp T_PROTO((
T_SPSS spss,
T_STR name
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSubscribe T_PROTO((
T_SPSS spss,
T_SPSS_SUBJECT subject
));
T_SPSS_API T_MSG T_ENTRY T_EXPORT TspssRead T_PROTO((
T_SPSS spss
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssWrite T_PROTO((
T_SPSS spss,
T_MSG msg
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssFlush T_PROTO((
T_SPSS spss
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssUnsubscribe T_PROTO((
T_SPSS spss,
T_SPSS_SUBJECT subject
));
T_SPSS_API void T_ENTRY T_EXPORT TspssRelease T_PROTO((
T_SPSS * spss
));
T_SPSS_API void T_ENTRY T_EXPORT TspssDestroy T_PROTO((
T_SPSS * spss
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssInit T_PROTO((void));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssInitThreads T_PROTO((void));

/* spssioq.c */
T_SPSS_API T_SPSS_IOQ_NODE T_ENTRY T_EXPORT TspssIOQNodeCreate T_PROTO((
T_SPSS_IOQ_NODE_TYPE type,
T_PTR ptr
));
T_SPSS_API T_SPSS_IOQ_NODE_TYPE T_ENTRY T_EXPORT TspssIOQNodeGetType T_PROTO((
T_SPSS_IOQ_NODE node
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssIOQNodePrint T_PROTO((
T_SPSS_IOQ_NODE node,
T_OUT_FUNC out_func
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssIOQNodeDestroy T_PROTO((
T_SPSS_IOQ_NODE node
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssIOQCreate T_PROTO((
T_SPSS_IOQ_NODE * head
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssIOQPut T_PROTO((
T_SPSS_IOQ_NODE head,
T_SPSS_IOQ_NODE_TYPE type,
T_PTR ptr
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssIOQIsEmpty T_PROTO((
T_SPSS_IOQ_NODE head
));
T_SPSS_API T_SPSS_IOQ_NODE T_ENTRY T_EXPORT TspssIOQGet T_PROTO((
T_SPSS_IOQ_NODE head,
T_BOOL flg_remove
));
T_SPSS_API T_MSG T_ENTRY T_EXPORT TspssIOQGetMsg T_PROTO((
T_SPSS spss,
T_SPSS_IOQ_NODE node
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssIOQPrint T_PROTO((
T_SPSS_IOQ_NODE head,
T_OUT_FUNC out_func
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssIOQDestroy T_PROTO((
T_SPSS_IOQ_NODE * head
));

/* spsssubj.c */
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSubjectCreate T_PROTO((
T_STR name,
T_BOOL flg_lb,
T_SPSS_SUBJECT * subject
));
T_SPSS_API void T_ENTRY T_EXPORT TspssSubjectAddref T_PROTO((
T_SPSS_SUBJECT subject
));
T_SPSS_API T_STR T_ENTRY T_EXPORT TspssSubjectGetName T_PROTO((
T_SPSS_SUBJECT subject
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSubjectGetLb T_PROTO((
T_SPSS_SUBJECT subject
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSubjectPrint T_PROTO((
T_SPSS_SUBJECT subject,
T_OUT_FUNC out_func
));
T_SPSS_API void T_ENTRY T_EXPORT TspssSubjectRelease T_PROTO((
T_SPSS_SUBJECT * subject
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssSubjectDestroy T_PROTO((
T_SPSS_SUBJECT * subject
));

/* spssstat.c */
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssStatCreate T_PROTO((
T_SPSS_STAT * stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatIncrNumOIOQDataMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API T_UINT4 T_ENTRY T_EXPORT TspssStatGetNumOIOQDataMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatDecrNumOIOQDataMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatIncrNumOIOQCtrlMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API T_UINT4 T_ENTRY T_EXPORT TspssStatGetNumOIOQCtrlMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatDecrNumOIOQCtrlMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatIncrNumIIOQDataMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API T_UINT4 T_ENTRY T_EXPORT TspssStatGetNumIIOQDataMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatDecrNumIIOQDataMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatIncrNumIIOQCtrlMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API T_UINT4 T_ENTRY T_EXPORT TspssStatGetNumIIOQCtrlMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatDecrNumIIOQCtrlMsgs T_PROTO((
T_SPSS_STAT stat
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssStatPrint T_PROTO((
T_SPSS_STAT stat,
T_OUT_FUNC out_func
));
T_SPSS_API void T_ENTRY T_EXPORT TspssStatDestroy T_PROTO((
T_SPSS_STAT * stat
));

/* spsscb.c */
T_SPSS_API T_CB T_ENTRY T_EXPORT TspssEventCbCreate T_PROTO((
T_SPSS spss,
T_SPSS_EVENT_CB_FUNC func,
T_CB_ARG arg
));
T_SPSS_API T_CB T_ENTRY T_EXPORT TspssEventCbLookup T_PROTO((
T_SPSS spss,
T_SPSS_EVENT_CB_FUNC func,
T_CB_ARG arg
));
T_SPSS_API void T_ENTRY T_EXPORT TspssEventCbCall T_PROTO((
T_SPSS spss,
T_SPSS_EVENT_CB_DATA cb_data
));
T_SPSS_API void T_ENTRY T_EXPORT TspssOpenEventCbCall T_PROTO((
T_SPSS spss,
T_BOOL status
));
T_SPSS_API void T_ENTRY T_EXPORT TspssReadEventCbCall T_PROTO((
T_SPSS spss
));
T_SPSS_API void T_ENTRY T_EXPORT TspssWriteEventCbCall T_PROTO((
T_SPSS spss
));
T_SPSS_API void T_ENTRY T_EXPORT TspssCloseEventCbCall T_PROTO((
T_SPSS spss
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssEventCbDestroy T_PROTO((
T_SPSS spss,
T_CB cb
));
T_SPSS_API T_BOOL T_ENTRY T_EXPORT TspssEventCbDestroyAll T_PROTO((
T_SPSS spss
));

#ifdef __cplusplus
}
#endif
