/*
 * Copyright (c) 1991-2006 TIBCO Software Inc.
 * All rights reserved.
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: //dev/packages/tkrnl/dev/68/src/rtworks/utpr.h#3 $
 */

/* This file is generated by cproto - do not edit! */

/* ../rtworks/utpr.h -- generated prototypes */

#ifndef T_UT_API
# ifndef T_OS_WIN32
# define T_UT_API
# else
# ifndef T_STATIC_LINK
# ifndef T_UT_SOURCE
# if !defined T_GENERATE_PROTOTYPES
# define T_UT_API __declspec(dllimport)
# else
# define T_UT_API
# endif
# else
# if !defined T_GENERATE_PROTOTYPES
# define T_UT_API __declspec(dllexport)
# else
# define T_UT_API
# endif
# endif
# else
# define T_UT_API
# endif /* T_STATIC_LINK */
# endif /* T_OS_WIN32 */
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* callback.c */
T_UT_API void T_ENTRY T_EXPORT TutCbPrint T_PROTO((
T_CB cb,
T_OUT_FUNC out_func
));
T_UT_API void T_ENTRY T_EXPORT TutCbPrintList T_PROTO((
T_CB_LIST cbl,
T_OUT_FUNC out_func
));
T_UT_API void T_ENTRY T_EXPORT TutCbPrintType T_PROTO((
T_CB_TYPE cbt,
T_OUT_FUNC outfunc
));
T_UT_API T_CB_LIST T_ENTRY T_EXPORT TutCbListCreate T_PROTO((
T_CB_TYPE cbt,
T_CB_OBJ owner
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListDestroy T_PROTO((
T_CB_LIST cbl
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListCall T_PROTO((
T_CB_LIST cbl,
T_CB_OBJ owner,
T_CB_DATA data
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListGetType T_PROTO((
T_CB_LIST cbl,
T_CB_TYPE * cbt
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListGetOwner T_PROTO((
T_CB_LIST cbl,
T_CB_OBJ * owner
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutCbListTraverse T_PROTO((
T_CB_LIST cbl,
T_CBLIST_TRAV_FUNC func,
T_PTR trav_arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListSetStartThresh T_PROTO((
T_CB_LIST cbl,
T_CB_PRIORITY pri
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListGetStartThresh T_PROTO((
T_CB_LIST cbl,
T_CB_PRIORITY * pri
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListSetCurrentThresh T_PROTO((
T_CB_LIST cbl,
T_CB_PRIORITY pri
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListGetCurrentThresh T_PROTO((
T_CB_LIST cbl,
T_CB_PRIORITY * pri
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListInsertCb T_PROTO((
T_CB_LIST cbl,
T_CB cb
));
T_UT_API T_CB T_ENTRY T_EXPORT TutCbListCbCreate T_PROTO((
T_CB_LIST cbl,
T_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutCbListCbLookup T_PROTO((
T_CB_LIST cbl,
T_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListRemoveCb T_PROTO((
T_CB_LIST cbl,
T_CB cb
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbListIsActive T_PROTO((
T_CB_LIST cbl
));
T_UT_API T_CB_TYPE T_ENTRY T_EXPORT TutCbTypeCreate T_PROTO((
T_INT4 type_number,
T_STR name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeSetLocalFlag T_PROTO((
T_CB_TYPE type,
T_BOOL flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeGetLocalFlag T_PROTO((
T_CB_TYPE type,
T_BOOL * flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeSetGlobFlag T_PROTO((
T_CB_TYPE type,
T_CB_GLOBAL_FLAG flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeGetGlobFlag T_PROTO((
T_CB_TYPE type,
T_CB_GLOBAL_FLAG * flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeGetName T_PROTO((
T_CB_TYPE cbtype,
T_STR * name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeGetNum T_PROTO((
T_CB_TYPE cbt,
T_INT4 * tn
));
T_UT_API T_CB_TYPE T_ENTRY T_EXPORT TutCbTypeLookup T_PROTO((
T_STR type_name
));
T_UT_API T_CB_TYPE T_ENTRY T_EXPORT TutCbTypeNumLookup T_PROTO((
T_INT4 type_number
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeGetCbList T_PROTO((
T_CB_TYPE cbtype,
T_CB_OBJ owner,
T_CB_LIST * cbl
));
T_UT_API T_CB T_ENTRY T_EXPORT TutCbTypeCbLookup T_PROTO((
T_CB_TYPE cbtype,
T_CB_OBJ owner,
T_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB_LIST T_ENTRY T_EXPORT TutCbTypeCbListCreate T_PROTO((
T_CB_TYPE cbt,
T_CB_OBJ owner
));
T_UT_API T_CB T_ENTRY T_EXPORT TutCbTypeCbCreate T_PROTO((
T_CB_TYPE cbt,
T_CB_OBJ cbobj,
T_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutCbTypeNumCbLookup T_PROTO((
T_INT4 type_num,
T_CB_OBJ owner,
T_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeNumCbDestroy T_PROTO((
T_INT4 type_num,
T_CB_OBJ owner,
T_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeNumCbCall T_PROTO((
T_INT4 type_num,
T_CB_OBJ owner,
T_CB_DATA data
));
T_UT_API void T_ENTRY T_EXPORT TutCbMergeCall T_PROTO((
T_CB_LIST objlist,
T_CB_LIST globlist,
T_CB_OBJ owner,
T_CB_DATA data
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeCall T_PROTO((
T_CB_TYPE cbt,
T_CB_OBJ owner,
T_CB_DATA data
));
T_UT_API T_CB T_ENTRY T_EXPORT TutCbCreateGlobal T_PROTO((
T_CB_TYPE cbt,
T_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbSetPriority T_PROTO((
T_CB cb,
T_CB_PRIORITY pri
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbGetPriority T_PROTO((
T_CB cb,
T_CB_PRIORITY * pri
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbSetArgument T_PROTO((
T_CB cb,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbGetArgument T_PROTO((
T_CB cb,
T_CB_ARG * arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbSetFunction T_PROTO((
T_CB cb,
T_CB_FUNC func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbGetFunction T_PROTO((
T_CB cb,
T_CB_FUNC * func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbDestroy T_PROTO((
T_CB cb
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbGetOwner T_PROTO((
T_CB cb,
T_CB_OBJ * owner
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbGetList T_PROTO((
T_CB cb,
T_CB_LIST * list
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbGetCbType T_PROTO((
T_CB cb,
T_CB_TYPE * type
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbObjClear T_PROTO((
T_CB_TYPE cbt,
T_CB_OBJ cbobj
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbTypeNumObjClear T_PROTO((
T_INT4 type_num,
T_CB_OBJ cbobj
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutCbTypeTraverse T_PROTO((
T_CBTYPE_TRAV_FUNC func,
T_PTR arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCbSetChangeFunction T_PROTO((
T_CB cb,
T_CB_CHANGE_CB_FUNC func,
T_CB_ARG arg
));

/* command.c */
T_UT_API T_INT4 T_ENTRY T_EXPORT TutMVSRedirect T_PROTO((
T_STR ddname
));
T_UT_API void T_ENTRY T_EXPORT TutMVSRedirFlush T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutCommandControlMsgConnSet T_PROTO((
T_PTR control_msg_conn
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutCommandControlMsgConnGet T_PROTO((void));
T_UT_API T_CB T_ENTRY T_EXPORT TutQuitCbCreate T_PROTO((
T_QUIT_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutQuitCbLookup T_PROTO((
T_QUIT_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRaiseFdLimit T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutCommandHelpPrint T_PROTO((
T_STR command
));
T_UT_API T_COMMAND T_ENTRY T_EXPORT TutCommandCreate T_PROTO((
T_STR name,
T_COMMAND_PARSE_FUNC parse_func
));
T_UT_API T_COMMAND T_ENTRY T_EXPORT TutCommandLookup T_PROTO((
T_STR name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandDestroy T_PROTO((
T_COMMAND command
));
T_UT_API void T_ENTRY T_EXPORT TutCommandParseStrInternal T_PROTO((
T_STR command_string,
T_BOOL control_msg
));
T_UT_API void T_ENTRY T_EXPORT TutCommandParseStr T_PROTO((
T_STR command_string
));
T_UT_API void T_ENTRY T_EXPORT TutCommandParseStrVa T_PROTO((
T_STR format_str,
...
));
T_UT_API void T_ENTRY T_EXPORT TutCommandParseTypedStrInternal T_PROTO((
T_STR command_string,
T_BOOL control_msg
));
T_UT_API void T_ENTRY T_EXPORT TutCommandParseTypedStr T_PROTO((
T_STR command_string
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandParseFile T_PROTO((
T_STR file_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandParseStdLicense T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandParseStdInternal T_PROTO((
T_STR module_name,
T_BOOL use_license_cmd,
T_STR local_cmd_fname,
T_STR old_module_name,
T_STR old_local_cmd_fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandParseStd T_PROTO((
T_STR module_name,
T_BOOL use_license_cmd,
T_STR local_cmd_fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandParseStd2 T_PROTO((
T_STR module_name,
T_BOOL use_license_cmd,
T_STR local_cmd_fname,
T_BOOL output_localdir_warning
));
T_UT_API void T_ENTRY T_EXPORT TutCommandRecordString T_PROTO((
T_STR command_string
));
T_UT_API void T_ENTRY T_EXPORT TutCommandMainLoop T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandGetYesOrNo T_PROTO((
T_STR prompt
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandSetParseFunc T_PROTO((
T_COMMAND command,
T_COMMAND_PARSE_FUNC parse_func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCommandSetHidden T_PROTO((
T_COMMAND command,
T_BOOL new_flag
));
T_UT_API void T_ENTRY T_EXPORT TutCbCommandSetFeedback T_PROTO((
T_OPTION option,
T_OPTION_CHANGE_CB_DATA data,
T_CB_ARG arg
));
T_UT_API void T_ENTRY T_EXPORT TutCommandPrintFeedback T_PROTO((
T_STR format_str,
...
));

/* deque.c */
T_UT_API void T_ENTRY T_EXPORT TutDqOpen T_PROTO((
T_DQ_NODE ** pdq
));
T_UT_API void T_ENTRY T_EXPORT TutDqClose T_PROTO((
T_DQ_NODE ** pdq
));
T_UT_API T_DQ_NODE * T_ENTRY T_EXPORT TutDqDetach T_PROTO((
T_DQ_NODE * dq,
T_DQ_NODE * d
));
T_UT_API void T_ENTRY T_EXPORT TutDqRightInsert T_PROTO((
T_DQ_NODE * d,
T_DQ_NODE * p
));
T_UT_API T_DQ_NODE * T_ENTRY T_EXPORT TutDqPop T_PROTO((
T_DQ_NODE * dq
));
T_UT_API T_DQ_NODE * T_ENTRY T_EXPORT TutDqFirst T_PROTO((
T_DQ_NODE * dq
));
T_UT_API T_DQ_NODE * T_ENTRY T_EXPORT TutDqLast T_PROTO((
T_DQ_NODE * dq
));

/* error.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPerrorSetEnable T_PROTO((
T_BOOL enable
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPerrorGetEnable T_PROTO((
T_BOOL * enable_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPerror T_PROTO((
T_STR user_msg
));
T_UT_API void T_ENTRY T_EXPORT TutErrNumSet T_PROTO((
T_INT4 err_num
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutErrNumGet T_PROTO((void));
T_UT_API T_INT4 * T_ENTRY T_EXPORT TutErrNumGetPtr T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutErrNumGetTrace T_PROTO((
T_PTR* traces,
T_INT4 max_traces
));
T_UT_API void T_ENTRY T_EXPORT TutErrNumSetC T_PROTO((
T_INT4 c_err_num
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutErrNumGetC T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutErrNumSetOs T_PROTO((
T_INT4 os_err_num
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutErrNumGetOs T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutErrNumSetSocket T_PROTO((
T_INT4 socket_err_num
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutErrNumGetSocket T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutErrNumSetVms T_PROTO((
T_INT4 c_err_num,
T_INT4 os_err_num
));
T_UT_API T_UTLIB_TSD T_ENTRY T_EXPORT TutErrNumSaveTsd T_PROTO((
T_ERR_SAVE err_save_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutErrNumSave T_PROTO((
T_ERR_SAVE err_save_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutErrNumRestoreTsd T_PROTO((
T_ERR_SAVE err_save,
T_UTLIB_TSD tsd
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutErrNumRestore T_PROTO((
T_ERR_SAVE err_save
));
T_UT_API void T_ENTRY T_EXPORT TutErrClearParams T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutErrOpenFile T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutErrCloseFile T_PROTO((void));
T_UT_API jmp_buf * T_ENTRY T_EXPORT TutErrGetJumpBufferPtr T_PROTO((void));
T_UT_API T_CHAR * T_ENTRY T_EXPORT TutGetDebugFlags T_PROTO((void));
T_UT_API T_STR T_ENTRY T_EXPORT TutErrNumToStr T_PROTO((
T_INT4 err_num
));
T_UT_API T_STR T_ENTRY T_EXPORT TutErrStrGet T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutErrStrCreate T_PROTO((
T_INT4 err_num,
T_STR err_str
));
T_UT_API void T_ENTRY T_EXPORT TutErrFeedbackSet T_PROTO((
T_ERR_FEEDBACK feedback
));
T_UT_API T_ERR_FEEDBACK T_ENTRY T_EXPORT TutErrFeedbackGet T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutErrSeveritySet T_PROTO((
T_ERR_SEVERITY severity
));
T_UT_API T_ERR_SEVERITY T_ENTRY T_EXPORT TutErrSeverityGet T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutErrParamSet T_PROTO((
T_INT4 param_num,
T_STR fmt_str,
T_PTR value_ptr
));
T_UT_API void T_ENTRY_VA T_EXPORT TutErrVReportParams T_PROTO((
T_STR func_name,
T_INT4 err_num,
va_list va_ptr
));
T_UT_API void T_ENTRY_VA T_EXPORT TutErrReportParams T_PROTO((
T_STR func_name,
T_INT4 err_num,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutErrReportParamsJmp T_PROTO((
T_STR func_name,
T_INT4 err_num,
jmp_buf err_buf,
...
));

/* fastmtex.c */
T_UT_API T_FAST_MUTEX T_ENTRY T_EXPORT TutFastMutexCreate T_PROTO((void));

T_UT_API T_BOOL T_ENTRY T_EXPORT TutFastMutexInit T_PROTO((
T_FAST_MUTEX fm
));

T_UT_API void T_ENTRY T_EXPORT TutFastMutexLock T_PROTO((
T_FAST_MUTEX fm
));

T_UT_API void T_ENTRY T_EXPORT TutFastMutexUnlock T_PROTO((
T_FAST_MUTEX fm
));

T_UT_API void T_ENTRY T_EXPORT TutFastMutexDestroy T_PROTO((
T_FAST_MUTEX fm
));

/* file.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutHasExtension T_PROTO((
T_STR file_name,
T_STR file_ext
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutBuildNFileName T_PROTO((
T_STR buffer,
T_INT4 buffer_size,
T_STR dir_name,
T_STR base,
T_STR ext
));
T_UT_API T_STR T_ENTRY T_EXPORT TutBuildFileName T_PROTO((
T_STR fname_return,
T_STR dir_name,
T_STR base,
T_STR ext
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutBuildNDirName T_PROTO((
T_STR buffer,
T_INT4 buffer_size,
T_STR base_dir,
T_STR sub_dir
));
T_UT_API T_STR T_ENTRY T_EXPORT TutBuildDirName T_PROTO((
T_STR dir_return,
T_STR base_dir,
T_STR sub_dir
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBuildBaseName T_PROTO((
T_STR dir_name,
T_STR base_name,
T_STR * base_return,
T_BOOL create_files
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutFileExists T_PROTO((
T_STR filename
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutMvsAccess T_PROTO((
T_CONST T_STR filename,
T_INT4 access_mode
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutFileWritable T_PROTO((
T_STR filename
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutDeleteFile T_PROTO((
T_STR fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBackupFile T_PROTO((
T_STR fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetFileOpenFunc T_PROTO((
T_FILE_OPEN_FUNC new_open_func
));
T_UT_API FILE * T_ENTRY T_EXPORT TutFOpen T_PROTO((
T_STR full_fname,
T_STR mode
));
T_UT_API FILE * T_ENTRY T_EXPORT TutOpenFile T_PROTO((
T_STR fname,
T_STR mode
));
T_UT_API FILE * T_ENTRY T_EXPORT TutLookupFile T_PROTO((
T_STR fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutFlushFile T_PROTO((
FILE * file
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetFileCloseFunc T_PROTO((
T_FILE_CLOSE_FUNC new_close_func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCloseFile T_PROTO((
FILE * file
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutFileTraverse T_PROTO((
T_FILE_TRAV_FUNC func,
T_PTR arg
));
T_UT_API void T_ENTRY T_EXPORT TutFileExamine T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFile T_PROTO((
T_STR file_name
));
T_UT_API void T_ENTRY T_EXPORT TutEditFile T_PROTO((
T_STR fname,
T_INT4 line
));
T_UT_API FILE * T_ENTRY T_EXPORT TutViewFilePtr T_PROTO((
FILE * file
));
T_UT_API T_SEARCH_PATH * T_ENTRY T_EXPORT TutPathCreate T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutPathAddDir T_PROTO((
T_SEARCH_PATH * sp,
T_STR dir
));
T_UT_API void T_ENTRY T_EXPORT TutPathDeleteDir T_PROTO((
T_SEARCH_PATH * sp,
T_STR dir
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutPathForEachDir T_PROTO((
T_SEARCH_PATH * sp,
T_SEARCH_PATH_DIR_TRAV_FUNC func,
T_PTR arg
));
T_UT_API void T_ENTRY T_EXPORT TutPathDestroy T_PROTO((
T_SEARCH_PATH * sp
));
T_UT_API T_STR T_ENTRY T_EXPORT TutPathFindFile T_PROTO((
T_SEARCH_PATH * sp,
T_STR fname,
T_STR pn
));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetFileName T_PROTO((
T_STR pn,
T_STR fn
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetNTmpFilePath T_PROTO((
T_STR buffer,
T_INT4 buffer_size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetTmpFilePath T_PROTO((
T_STR outfpath
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutFileGetSize T_PROTO((
T_STR file_name,
T_INT4 * size_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutFileGetAccessTimes T_PROTO((
T_STR file_name,
T_REAL8 * last_access_time_return,
T_REAL8 * last_modified_time_return,
T_REAL8 * last_status_change_time_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutFileExplodeName T_PROTO((
T_CONST T_STR pn,
T_STR * dir_ptr,
T_STR * base_ptr,
T_STR * ext_ptr
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutMkdir T_PROTO((
T_STR new_dir_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRmdir T_PROTO((
T_STR dir_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutChdir T_PROTO((
T_STR new_dir
));
T_UT_API T_DIR T_ENTRY T_EXPORT TutOpenDir T_PROTO((
T_STR dirname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCloseDir T_PROTO((
T_DIR dir
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutReadDir T_PROTO((
T_DIR dir,
T_DIRENT dirent
));
T_UT_API T_DIRECTORY_TYPE T_ENTRY T_EXPORT TutMvsDirectoryType T_PROTO((
T_STR dir_name
));
T_UT_API T_DIRECTORY_TYPE T_ENTRY T_EXPORT TutGetRtHomeDirectoryType T_PROTO((void));

/* format.c */
T_UT_API T_INT_FORMAT T_ENTRY T_EXPORT TutGetIntFormat T_PROTO((void));
T_UT_API T_REAL_FORMAT T_ENTRY T_EXPORT TutGetRealFormat T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutIntFormatToStr T_PROTO((
T_INT_FORMAT int_format,
T_STR * format_str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRealFormatToStr T_PROTO((
T_REAL_FORMAT real_format,
T_STR * format_str_return
));
T_UT_API void T_ENTRY T_EXPORT TutSwapTwoBytes T_PROTO((
T_STR val_in_out
));
T_UT_API void T_ENTRY T_EXPORT TutSwapFourBytes T_PROTO((
T_STR val_in_out
));
T_UT_API void T_ENTRY T_EXPORT TutSwapEightBytes T_PROTO((
T_STR val_in_out
));
T_UT_API void T_ENTRY T_EXPORT TutSwapSixteenBytes T_PROTO((
T_STR val_in_out
));
T_UT_API unsigned short T_ENTRY T_EXPORT TutVmsSwapTwoBytes T_PROTO((
unsigned short num
));
T_UT_API unsigned long T_ENTRY T_EXPORT TutVmsSwapFourBytes T_PROTO((
unsigned long num
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal4IeeeToDecF T_PROTO((
T_REAL4 * real4_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal4DecFToIeee T_PROTO((
T_REAL4 * real4_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal4IeeeToIbm370 T_PROTO((
T_REAL4 * real4_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal4Ibm370ToIeee T_PROTO((
T_REAL4 * real4_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal4DecFToIbm370 T_PROTO((
T_REAL4 * real4_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal4Ibm370ToDecF T_PROTO((
T_REAL4 * real4_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8IeeeToDecD T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8IeeeToDecG T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8DecDToIeee T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8DecDToDecG T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8DecGToIeee T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8DecGToDecD T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8IeeeToIbm370 T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8Ibm370ToIeee T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8DecDToIbm370 T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8Ibm370ToDecD T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8DecGToIbm370 T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapReal8Ibm370ToDecG T_PROTO((
T_REAL8 * real8_in_out,
T_INT_FORMAT src_int_format,
T_INT_FORMAT dest_int_format
));
T_UT_API T_CHAR_FORMAT T_ENTRY T_EXPORT TutGetCharFormatSystemDefault T_PROTO((void));
T_UT_API T_CHAR_FORMAT T_ENTRY T_EXPORT TutGetCharFormat T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetCharFormat T_PROTO((
T_CHAR_FORMAT char_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapStr T_PROTO((
T_STR str_in_out,
T_CHAR_FORMAT_DRIVER driver
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSwapChar T_PROTO((
T_STR char_in_out,
T_CHAR_FORMAT_DRIVER driver
));
T_UT_API T_CHAR_FORMAT T_ENTRY T_EXPORT TutCharFormatLookup T_PROTO((
T_STR name
));
T_UT_API T_STR T_ENTRY T_EXPORT TutCharFormatNameLookup T_PROTO((
T_CHAR_FORMAT number
));
T_UT_API T_CHAR_FORMAT_DRIVER T_ENTRY T_EXPORT TutCharFormatDriverLookup T_PROTO((
T_CHAR_FORMAT src_format,
T_CHAR_FORMAT dest_format
));
T_UT_API T_CHAR_FORMAT_INFO T_ENTRY T_EXPORT TutCharFormatInfoLookup T_PROTO((
T_CHAR_FORMAT src_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutConvertStr T_PROTO((
T_STR src_str,
T_CHAR_FORMAT src_char_format,
T_STR * dest_str,
T_CHAR_FORMAT dest_char_format
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutCompareUni T_PROTO((
T_CHAR_EL p1,
T_CHAR_EL p2
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutCompareSrcCp T_PROTO((
T_CHAR_EL p1,
T_CHAR_EL p2
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutStrLenByte T_PROTO((
T_STR pInBuf,
T_CHAR_FORMAT InBufCharFormat
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrCpy T_PROTO((
T_STR pOutBuf,
T_CONST T_STR pInBuf,
T_CHAR_FORMAT InBufCharFormat
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutTextGetSize T_PROTO((
T_STR str,
T_CHAR_FORMAT char_format
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutConvertUcs2ToUtf8 T_PROTO((
T_WSTR wstr,
T_STR * str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutConvertUtf8ToUcs2 T_PROTO((
T_STR str,
T_WSTR * wstr_return
));

/* hash.c */
T_UT_API T_INT4 T_ENTRY T_EXPORT TutRoundUpToPowerOf2 T_PROTO((
T_INT4 value
));
T_UT_API void T_ENTRY TutHashCreateBuckets T_PROTO((
T_HASH_TABLE table,
T_INT4 init_size
));
T_UT_API T_HASH_TABLE T_ENTRY T_EXPORT TutHashCreate T_PROTO((
T_INT4 init_size,
T_HASH_CALC_FUNC hash_func,
T_HASH_TEST_FUNC test_func
));
T_UT_API T_HASH_TABLE T_ENTRY T_EXPORT TutHashCreateInt T_PROTO((
T_INT4 init_size
));
T_UT_API T_HASH_TABLE T_ENTRY T_EXPORT TutHashCreateStr T_PROTO((
T_INT4 init_size
));
T_UT_API T_HASH_TABLE T_ENTRY T_EXPORT TutHashCreateStri T_PROTO((
T_INT4 init_size
));
T_UT_API T_HASH_TABLE T_ENTRY T_EXPORT TutHashCreatePtr T_PROTO((
T_INT4 init_size
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutHashGetSize T_PROTO((
T_HASH_TABLE table
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutHashGetCollisions T_PROTO((
T_HASH_TABLE table
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutHashGetReferenceCounted T_PROTO((
T_HASH_TABLE table
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutHashSetReferenceCounted T_PROTO((
T_HASH_TABLE table,
T_BOOL ref_counted
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashLookup T_PROTO((
T_HASH_TABLE table,
T_PTR key
));
T_UT_API T_HASH_BUCKET T_ENTRY T_EXPORT TutHashLookupBucket T_PROTO((
T_HASH_TABLE table,
T_PTR key
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashLookupInt T_PROTO((
T_HASH_TABLE table,
T_INT4 key
));
T_UT_API T_HASH_CALC_FUNC T_ENTRY T_EXPORT TutHashGetHashFunc T_PROTO((
T_HASH_TABLE table
));
T_UT_API T_HASH_TEST_FUNC T_ENTRY T_EXPORT TutHashGetTestFunc T_PROTO((
T_HASH_TABLE table
));
T_UT_API T_HASH_BUCKET T_ENTRY T_EXPORT TutHashGetFirstBucket T_PROTO((
T_HASH_TABLE table
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashTraverse T_PROTO((
T_HASH_TABLE table,
T_HASH_TRAV_FUNC func,
T_PTR arg
));
T_UT_API void T_ENTRY T_EXPORT TutHashInsertBucket T_PROTO((
T_HASH_TABLE table,
T_HASH_BUCKET bucket,
T_HASH_CALC_FUNC hash_func
));
T_UT_API void T_ENTRY T_EXPORT TutHashResizeEx T_PROTO((
T_HASH_TABLE table,
T_INT4 new_size,
T_HASH_CALC_FUNC hash_func
));
T_UT_API void T_ENTRY T_EXPORT TutHashResize T_PROTO((
T_HASH_TABLE table,
T_INT4 new_size
));
T_UT_API void T_ENTRY T_EXPORT TutHashInsert T_PROTO((
T_HASH_TABLE table,
T_PTR key,
T_PTR value
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashReplace T_PROTO((
T_HASH_TABLE table,
T_PTR key,
T_PTR new_value
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashBucketGetValue T_PROTO((
T_HASH_BUCKET bucket
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashBucketSetValue T_PROTO((
T_HASH_BUCKET bucket,
T_PTR new_value
));
T_UT_API T_HASH_BUCKET T_ENTRY T_EXPORT TutHashDeleteBucket T_PROTO((
T_HASH_TABLE table,
T_PTR key
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashDelete T_PROTO((
T_HASH_TABLE table,
T_PTR key
));
T_UT_API void T_ENTRY T_EXPORT TutHashReset T_PROTO((
T_HASH_TABLE table,
T_HASH_RESET_FUNC reset_func,
T_PTR reset_arg
));
T_UT_API void T_ENTRY T_EXPORT TutHashResetFreeKey T_PROTO((
T_HASH_TABLE table
));
T_UT_API void T_ENTRY T_EXPORT TutHashResetFreeValue T_PROTO((
T_HASH_TABLE table
));
T_UT_API void T_ENTRY T_EXPORT TutHashResetFreeKeyValue T_PROTO((
T_HASH_TABLE table
));
T_UT_API void T_ENTRY T_EXPORT TutHashDestroy T_PROTO((
T_HASH_TABLE table,
T_HASH_DESTROY_FUNC destroy_func,
T_PTR destroy_arg
));
T_UT_API void T_ENTRY T_EXPORT TutHashDestroyFreeKey T_PROTO((
T_HASH_TABLE table
));
T_UT_API void T_ENTRY T_EXPORT TutHashDestroyFreeValue T_PROTO((
T_HASH_TABLE table
));
T_UT_API void T_ENTRY T_EXPORT TutHashDestroyFreeKeyValue T_PROTO((
T_HASH_TABLE table
));
T_UT_API void T_ENTRY T_EXPORT TutHashDump T_PROTO((
T_HASH_TABLE table,
T_OUT_FUNC output_func
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashSort T_PROTO((
T_HASH_TABLE table,
T_INT4 * array_size_return,
T_HASH_SORT_CMP_FUNC cmp_func,
T_HASH_SORT_SELECT_FUNC select_func
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashSortKeys T_PROTO((
T_HASH_TABLE table,
T_INT4 * array_size_return,
T_HASH_SORT_CMP_FUNC cmp_func,
T_HASH_SORT_SELECT_FUNC select_func
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutHashSortTraverse T_PROTO((
T_HASH_TABLE table,
T_HASH_SORT_TRAV_FUNC func,
T_PTR arg,
T_HASH_SORT_CMP_FUNC cmp_func,
T_HASH_SORT_SELECT_FUNC select_func
));

/* interupt.c */
T_UT_API void T_ENTRY T_EXPORT TutInterruptReset T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutInterruptGet T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutInterruptIncr T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutInterruptSet T_PROTO((
T_INT4 new_value
));
T_UT_API void T_ENTRY_VA T_EXPORT TutSigintHandler T_PROTO((
int dummy
));
T_UT_API void T_ENTRY T_EXPORT TutInterruptInit T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutReadAtomic T_PROTO((
T_INT4 fd,
T_PTR ptr,
T_INT4 size
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutWriteAtomic T_PROTO((
T_INT4 fd,
T_PTR ptr,
T_INT4 size
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutFsyncAtomic T_PROTO((
T_INT4 fd
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutUnlinkAtomic T_PROTO((
T_STR path
));

/* lex.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetFileReadFunc T_PROTO((
T_FILE_READ_FUNC new_read_func
));
T_UT_API void T_ENTRY_VA T_EXPORT TutLexQuietLongjmpErrorFunc T_PROTO((
T_LEX lexer,
T_STR format_str,
va_list var_arg_ptr,
jmp_buf jump_buffer
));
T_UT_API void T_ENTRY_VA T_EXPORT TutLexLongjmpErrorFunc T_PROTO((
T_LEX lexer,
T_STR format_str,
va_list var_arg_ptr,
jmp_buf jump_buffer
));
T_UT_API void T_ENTRY_VA T_EXPORT TutLexError T_PROTO((
T_LEX lexer,
T_STR format_str,
...
));
T_UT_API void T_ENTRY T_EXPORT TutLexSetUserErrorFunc T_PROTO((
T_LEX_ERROR_FUNCTION error_func
));
T_UT_API T_STR T_ENTRY T_EXPORT TutLexTokenToString T_PROTO((
T_INT4 token,
T_STR str_rep_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLexPrintReservedWords T_PROTO((
T_OUT_FUNC func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLexAddReservedWord T_PROTO((
T_STR name,
T_INT4 value
));
T_UT_API T_CB T_ENTRY T_EXPORT TutLexTokenCbCreate T_PROTO((
T_LEX lexer,
T_LEX_TOKEN_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutLexTokenCbLookup T_PROTO((
T_LEX lexer,
T_LEX_TOKEN_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_LEX T_ENTRY_VA T_EXPORT TutLexCreate T_PROTO((
T_LEX_ATT lex_att,
...
));
T_UT_API void T_ENTRY T_EXPORT TutLexDestroy T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAccept T_PROTO((
T_LEX lexer,
T_INT4 token
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptFileName T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptGuidStr T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptSlot T_PROTO((
T_LEX lexer
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLexAcceptSlotOrAlias T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptSignedReal T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptSignedInt T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptUnsignedInt T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptId T_PROTO((
T_LEX lexer
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLexAcceptBool T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexAcceptPattern T_PROTO((
T_LEX lexer
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLexGetCurrentPositionInFile T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexSkipToEoln T_PROTO((
T_LEX lexer
));
T_UT_API void T_ENTRY T_EXPORT TutLexGobbleWhitespace T_PROTO((
T_LEX lexer
));

/* list.c */
T_UT_API T_INT4 T_ENTRY T_EXPORT TutListLength T_PROTO((
T_LST_NODE * head
));
T_UT_API T_LST_NODE * T_ENTRY T_EXPORT TutListDelete T_PROTO((
T_LST_NODE ** headp,
T_LST_NODE * p
));
T_UT_API void T_ENTRY T_EXPORT TutListTravDel T_PROTO((
T_LST_NODE ** headp,
T_LST_TRAV_DEL_FUNC del_func,
T_PTR arg
));
T_UT_API T_LST_NODE * T_ENTRY T_EXPORT TutListEnd T_PROTO((
T_LST_NODE * head
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutListPos T_PROTO((
T_LST_NODE * front,
T_LST_NODE * element
));

/* lobe.c */
T_UT_API T_HASH T_ENTRY T_EXPORT TutLobeTable T_PROTO((void));
T_UT_API T_LOBE T_ENTRY T_EXPORT TutLobeLookup T_PROTO((
T_INT4 lobe_num
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLobeGetSize T_PROTO((
T_LOBE lobe
));
T_UT_API T_LOBE T_ENTRY T_EXPORT TutLobeStringDeclare T_PROTO((
T_INT4 lobe_num
));
T_UT_API T_LOBE T_ENTRY T_EXPORT TutLobeDeclare T_PROTO((
T_INT4 lobe_num,
T_INT4 size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutLobeFindValue T_PROTO((
T_PTR ptr,
T_LOBE lobe
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLobeCheckSet T_PROTO((
T_PTR ptr,
T_LOBE lobe,
T_PTR vptr
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLobeSet T_PROTO((
T_PTR ptr,
T_LOBE lobe,
T_PTR vptr
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLobeGet T_PROTO((
T_PTR ptr,
T_LOBE lobe,
T_PTR vptr
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutLobeDelete T_PROTO((
T_PTR ptr,
T_LOBE lobe
));
T_UT_API void T_ENTRY T_EXPORT TutLobeClear T_PROTO((
T_PTR ptr
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutLobeTraverse T_PROTO((
T_LOBE lobe,
T_HASH_TRAV_FUNC func,
T_PTR arg
));

/* mempool.c */
T_UT_API T_MEMORY_POOL_FACTORY T_ENTRY T_EXPORT TutMemPoolFactoryCreate T_PROTO((
T_INT4 item_size,
T_INT4 pool_pages
));

T_UT_API void T_ENTRY T_EXPORT TutMemPoolFactorySetZeroed T_PROTO((
T_MEMORY_POOL_FACTORY factory,
T_BOOL value
));

T_UT_API T_PTR T_ENTRY T_EXPORT TutMemPoolFactoryItemCreate T_PROTO((
T_MEMORY_POOL_FACTORY factory
));

T_UT_API void T_ENTRY T_EXPORT TutMemPoolItemDestroy T_PROTO((
T_PTR *item,
T_MEMORY_POOL_FACTORY factory
));

/* option.c */
T_UT_API T_STR T_ENTRY T_EXPORT TutRealToStrCopy T_PROTO((
T_REAL8 real8,
T_STR str_return
));
T_UT_API T_STR T_ENTRY T_EXPORT TutRealToStr T_PROTO((
T_REAL8 real8
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionReadLock T_PROTO((
T_OPTION option
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionWriteLock T_PROTO((
T_OPTION option
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionUpgradeLock T_PROTO((
T_OPTION option
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionUnlock T_PROTO((
T_OPTION option
));
T_UT_API T_STR T_ENTRY T_EXPORT TutOptionTypeToStr T_PROTO((
T_OPT_TYPE type
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionVerifyNonNeg T_PROTO((
T_OPTION option,
T_PTR value,
T_PTR dummy
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionVerifyInt2 T_PROTO((
T_OPTION option,
T_PTR value,
T_PTR dummy
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionVerifyLogFile T_PROTO((
T_OPTION option,
T_PTR value,
T_PTR arg
));
T_UT_API void T_ENTRY T_EXPORT TutCbOptionCopyBool2 T_PROTO((
T_OPTION option,
T_OPTION_CHANGE_CB_DATA data,
T_CB_ARG arg
));
T_UT_API void T_ENTRY T_EXPORT TutCbOptionCopyInt42 T_PROTO((
T_OPTION option,
T_OPTION_CHANGE_CB_DATA data,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionRealNumberFormatVf T_PROTO((
T_OPTION option,
T_PTR value,
T_PTR dummy
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutDefaultUniqueSubject T_PROTO((
T_STR buffer,
T_INT4 buffer_size,
T_INT4 pid
));
T_UT_API T_STR T_ENTRY T_EXPORT TutOptionGetUniqueSubjectDefault T_PROTO((
T_STR unique_subject,
T_INT4 pid
));
T_UT_API T_HASH_TABLE T_ENTRY T_EXPORT TutGetOptionTable T_PROTO((void));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutOptionCreate T_PROTO((
T_STR name,
T_OPT_TYPE type
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionDestroy T_PROTO((
T_OPTION option
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutOptionLookup T_PROTO((
T_STR name
));
T_UT_API T_OPTION * T_ENTRY T_EXPORT TutOptionSort T_PROTO((
T_INT4 * num_options_return
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutOptionTraverse T_PROTO((
T_OPTION_TRAV_FUNC func,
T_PTR arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionLegValAdd T_PROTO((
T_OPTION option,
T_STR val
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutOptionLegValTraverse T_PROTO((
T_OPTION option,
T_OPTION_LEGVAL_TRAV_FUNC func,
T_PTR arg
));
T_UT_API void T_ENTRY T_EXPORT TutOptionDump T_PROTO((
T_STR name,
T_OUT_FUNC output_func
));
T_UT_API T_STR T_ENTRY T_EXPORT TutOptionValToStr T_PROTO((
T_OPTION option
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionParseValue T_PROTO((
T_OPTION option,
T_LEX lexer
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionCreateFromLexer T_PROTO((
T_STR option_name,
T_LEX lexer
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetBool T_PROTO((
T_OPTION option,
T_BOOL * bool_val_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetEnum T_PROTO((
T_OPTION option,
T_STR * enum_val_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetNum T_PROTO((
T_OPTION option,
T_REAL8 * num_val_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetStr T_PROTO((
T_OPTION option,
T_STR * str_val_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetEnumList T_PROTO((
T_OPTION option,
T_STR_LIST * enum_list_val_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetStrList T_PROTO((
T_OPTION option,
T_STR_LIST * str_list_val_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetKnown T_PROTO((
T_OPTION option,
T_BOOL * known_flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetType T_PROTO((
T_OPTION option,
T_OPT_TYPE * opt_type
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetRequired T_PROTO((
T_OPTION option,
T_BOOL * required_flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetProtected T_PROTO((
T_OPTION option,
T_BOOL * protect_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetReadOnly T_PROTO((
T_OPTION option,
T_BOOL * read_only_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionGetVerifyFunc T_PROTO((
T_OPTION option,
T_OPTION_VERIFY_FUNC * verify_func_return
));
T_UT_API T_STR T_ENTRY T_EXPORT TutOptionGetName T_PROTO((
T_OPTION option
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetRequired T_PROTO((
T_OPTION option,
T_BOOL n
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetProtected T_PROTO((
T_OPTION option,
T_BOOL protect
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetReadOnly T_PROTO((
T_OPTION option,
T_BOOL read_only
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetVerifyFunc T_PROTO((
T_OPTION option,
T_OPTION_VERIFY_FUNC verify_func,
T_PTR verify_arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetUnknown T_PROTO((
T_OPTION option
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetBool T_PROTO((
T_OPTION option,
T_BOOL bool_val
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetEnum T_PROTO((
T_OPTION option,
T_STR enum_val
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetEnumList T_PROTO((
T_OPTION option,
T_STR_LIST enum_list
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetNum T_PROTO((
T_OPTION option,
T_REAL8 num_value
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetStr T_PROTO((
T_OPTION option,
T_STR str_val
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionSetStrList T_PROTO((
T_OPTION option,
T_STR_LIST str_list
));
T_UT_API T_CB T_ENTRY T_EXPORT TutOptionChangeCbCreate T_PROTO((
T_OPTION option,
T_OPTION_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutOptionChangeCbLookup T_PROTO((
T_OPTION option,
T_OPTION_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_STR T_ENTRY T_EXPORT TutOptionGetValue T_PROTO((
T_STR name
));
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutOptionGetNumValue T_PROTO((
T_STR name
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutOptionSet T_PROTO((
T_STR name,
T_PTR option_value
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionUnset T_PROTO((
T_STR name
));
T_UT_API void T_ENTRY T_EXPORT TutOptionSetNumValue T_PROTO((
T_STR name,
T_REAL8 value
));
T_UT_API T_BOOL T_ENTRY T_EXPORT Tutptstcp T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutCbOptionCopyBool T_PROTO((
T_OPTION option,
T_OPTION_CHANGE_CB_DATA data,
T_CB_ARG arg
));
T_UT_API void T_ENTRY T_EXPORT TutCbOptionCopyInt4 T_PROTO((
T_OPTION option,
T_OPTION_CHANGE_CB_DATA data,
T_CB_ARG arg
));
T_UT_API T_HASH_TABLE T_ENTRY T_EXPORT TutGetNamedOptionTable T_PROTO((
T_STR name
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutOptionNamedLookup T_PROTO((
T_STR name,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutOptionNamedDump T_PROTO((
T_STR name,
T_STR option_name,
T_OUT_FUNC output_func
));

/* ptrary.c */
T_UT_API T_PTR_ARY T_ENTRY T_EXPORT TutPtrAryCreate T_PROTO((
T_INT4 size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryClear T_PROTO((
T_PTR_ARY ptr_ary,
T_PTR_ARY_USER_FUNC user_func,
T_PTR arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryAppend T_PROTO((
T_PTR_ARY dest,
T_PTR src,
T_INT4 * idx_ptr
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryDestroy T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR_ARY_USER_FUNC user_func,
T_PTR arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryRemoveItemAtIndex T_PROTO((
T_PTR_ARY ptr_ary,
T_INT4 indx,
T_PTR * item
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryRemove T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR item
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryRemoveAll T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR item,
T_INT4 * counter
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryGetItemIndex T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR item,
T_INT4 * item_pos
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryItemExists T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR item
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryGetItemCount T_PROTO((
T_PTR_ARY_STRUCT * pointer_array,
T_INT4 * count
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryGetItemAtIndex T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_INT4 item_index,
T_PTR * item
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryReplaceItemAtIndex T_PROTO((
T_PTR_ARY ptr_ary,
T_PTR new_item,
T_INT4 item_index,
T_PTR * old_item
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrArySwapItems T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_INT4 item_index1,
T_INT4 item_index2
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryInsertBefore T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR index_item,
T_PTR new_item
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryInsertAfter T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR index_item,
T_PTR new_item
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryInsertItemAtIndex T_PROTO((
T_PTR_ARY_STRUCT * ptr_ary,
T_PTR new_item,
T_INT4 item_index
));
T_UT_API T_PTR * T_ENTRY T_EXPORT TutPtrAryGetArray T_PROTO((
T_PTR_ARY ptr_ary
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrArySort T_PROTO((
T_PTR_ARY ptr_ary,
T_PTR_ARY_CMP_FUNC compare_func
));
T_UT_API T_CB T_ENTRY T_EXPORT TutPtrAryChangeCbCreate T_PROTO((
T_PTR_ARY ptr_ary,
T_PTR_ARY_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutPtrAryChangeCbLookup T_PROTO((
T_PTR_ARY ptr_ary,
T_PTR_ARY_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPtrAryAppendAll T_PROTO((
T_PTR_ARY dest,
T_PTR_ARY src,
T_INT4 * begin_idx_ptr,
T_INT4 * end_idx_ptr
));

/* ptrdeque.c */
T_UT_API T_PDQ_NODE * T_ENTRY T_EXPORT TutFindPdqNode T_PROTO((
T_PDQ_NODE * pdq,
T_PTR p
));
T_UT_API T_PDQ_NODE * T_ENTRY T_EXPORT TutAddPdqNode T_PROTO((
T_PDQ_NODE * pdq,
T_PTR p
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutDeletePdqNode T_PROTO((
T_PDQ_NODE * pdq,
T_PTR p
));

/* ptrqueue.c */
T_UT_API T_PTR T_ENTRY T_EXPORT TutPqPop T_PROTO((
T_PQ_HEADER * hdr
));
T_UT_API void T_ENTRY T_EXPORT TutPqClose T_PROTO((
T_PQ_HEADER * hdr
));
T_UT_API void T_ENTRY T_EXPORT TutPqPush T_PROTO((
T_PQ_HEADER * hdr,
T_PTR p
));
T_UT_API void T_ENTRY T_EXPORT TutPqRInsert T_PROTO((
T_PQ_HEADER * hdr,
T_PTR * ptr,
T_PQ_NODE * node
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutPqInsert T_PROTO((
T_PQ_HEADER * hdr,
T_PTR ptr,
T_PQ_CMP_FUNC cmp_func
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutPqDelete T_PROTO((
T_PQ_HEADER * hdr,
T_PTR p
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutPqFind T_PROTO((
T_PQ_HEADER * hdr,
T_PTR ptr
));
T_UT_API void T_ENTRY T_EXPORT TutPqAdd T_PROTO((
T_PQ_HEADER * hdr,
T_PTR p
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutPqCount T_PROTO((
T_PQ_HEADER * hdr
));

/* bppq.c */
T_UT_API T_PTR T_ENTRY T_EXPORT TutBppqPop T_PROTO((
T_BPPQ_HEADER * hdr
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutBppqDelete T_PROTO((
T_BPPQ_HEADER * hdr,
T_PQ_NODE *pqn,
T_INT4 * pos
));
T_UT_API void T_ENTRY T_EXPORT TutBppqClose T_PROTO((
T_BPPQ_HEADER * hdr
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutBppqBAppend T_PROTO((
T_BPPQ_HEADER * hdr,
T_PTR ptr
));
T_UT_API void T_ENTRY T_EXPORT TutBppqNInsert T_PROTO((
T_BPPQ_HEADER * hdr,
T_PTR ptr,
T_INT4 pos
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutBppqInsert T_PROTO((
T_BPPQ_HEADER * hdr,
T_PTR ptr,
T_PQ_CMP_FUNC cmp_func
));

/* ptrstack.c */
T_UT_API T_PST_NODE * T_ENTRY T_EXPORT TutFindPstNode T_PROTO((
T_PST_NODE * st,
char * p
));
T_UT_API T_PST_NODE * T_ENTRY T_EXPORT TutPushPstNode T_PROTO((
T_PST_NODE ** pst,
char * p
));
T_UT_API char * T_ENTRY T_EXPORT TutPopPstNode T_PROTO((
T_PST_NODE ** pst
));

/* queue.c */
T_UT_API T_Q_NODE * T_ENTRY T_EXPORT TutQueuePop T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp
));
T_UT_API void T_ENTRY T_EXPORT TutQueueAppend T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp,
T_Q_NODE * p
));
T_UT_API void T_ENTRY T_EXPORT TutQueueClose T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp
));
T_UT_API void T_ENTRY T_EXPORT TutQueuePush T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp,
T_Q_NODE * p
));
T_UT_API void T_ENTRY T_EXPORT TutQueueRightInsert T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp,
T_Q_NODE * p,
T_Q_NODE ** pp
));
T_UT_API T_Q_NODE * T_ENTRY T_EXPORT TutQueueRightDetach T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp,
T_Q_NODE ** pp
));
T_UT_API T_Q_NODE ** T_ENTRY T_EXPORT TutQueueLeftFind T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp,
T_Q_NODE * p,
T_Q_CMP_FUNC cmp_func
));
T_UT_API void T_ENTRY T_EXPORT TutQueueInsert T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp,
T_Q_NODE * p,
T_Q_CMP_FUNC cmp_func
));
T_UT_API T_Q_NODE * T_ENTRY T_EXPORT TutQueueDelete T_PROTO((
T_Q_NODE ** frontp,
T_Q_NODE ** rearp,
T_Q_NODE * p
));

/* safestr.c */
T_UT_API void T_ENTRY T_EXPORT TutSafeStringPrepend T_PROTO((
T_SAFE_STR_STRUCT * dest,
T_STR src
));
T_UT_API T_SAFE_STR_STRUCT T_ENTRY T_EXPORT TutSafeStringQCreate T_PROTO((
T_INT4 q
));
T_UT_API T_SAFE_STR_STRUCT T_ENTRY T_EXPORT TutSafeStringCreate T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringDestroy T_PROTO((
T_SAFE_STR_STRUCT safe_str
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringQAppend T_PROTO((
T_SAFE_STR_STRUCT * dest,
T_STR src,
T_INT4 q
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringAppend T_PROTO((
T_SAFE_STR_STRUCT * dest,
T_STR src
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringQAppendChar T_PROTO((
T_SAFE_STR_STRUCT * dest,
T_CHAR c,
T_INT4 q
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringAppendChar T_PROTO((
T_SAFE_STR_STRUCT * dest,
T_CHAR c
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringClear T_PROTO((
T_SAFE_STR_STRUCT * safe_str
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringQCopy T_PROTO((
T_SAFE_STR_STRUCT * safe_str,
T_STR new_str,
T_INT4 q
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringCopy T_PROTO((
T_SAFE_STR_STRUCT * safe_str,
T_STR new_str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSafeStringResize T_PROTO((
T_SAFE_STR_STRUCT * ssp,
T_INT4 new_size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSafeStringShorten T_PROTO((
T_SAFE_STR_STRUCT * ssp,
T_INT4 nb
));
T_UT_API void T_ENTRY T_EXPORT TutSafeStringAppendInt4 T_PROTO((
T_SAFE_STR_STRUCT * dest,
T_INT4 int4_val
));

/* shrq.c */
T_UT_API void T_ENTRY_VA T_EXPORT TutShrQInit T_PROTO((
T_SHRQ sq
));

T_UT_API void T_ENTRY_VA T_EXPORT TutShrQInsert T_PROTO((
T_SHRQ sq,
T_SHRQ_ITEM item
));

T_UT_API T_SHRQ_ITEM T_ENTRY_VA T_EXPORT TutShrQRemove T_PROTO((
T_SHRQ sq
));

/* stack.c */
T_UT_API void T_ENTRY T_EXPORT TutStackPush T_PROTO((
T_ST_NODE ** headp,
T_ST_NODE * p
));
T_UT_API T_ST_NODE * T_ENTRY T_EXPORT TutStackPop T_PROTO((
T_ST_NODE ** headp
));
T_UT_API void T_ENTRY T_EXPORT TutStackClose T_PROTO((
T_ST_NODE ** headp
));

/* strutil.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutIsWhiteEmptyOrNullStr T_PROTO((
T_STR str
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrStripChar T_PROTO((
T_STR original,
T_INT4 ch
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrReplaceOne T_PROTO((
T_STR s,
T_STR o,
T_STR n,
T_INT4 * status_return
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrReplaceAll T_PROTO((
T_STR s,
T_STR o,
T_STR n
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrNLwr T_PROTO((
T_STR dest,
T_STR src,
T_INT4 dest_size
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrNUpr T_PROTO((
T_STR dest,
T_STR src,
T_INT4 dest_size
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrLwr T_PROTO((
T_STR dest,
T_STR src
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrUpr T_PROTO((
T_STR dest,
T_STR src
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutStrCmpi T_PROTO((
T_STR str1,
T_STR str2
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutStrNCmpi T_PROTO((
T_STR str1,
T_STR str2,
T_INT4 n
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrDup T_PROTO((
T_STR str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetSubStr T_PROTO((
T_STR str,
T_STR substr,
T_INT4 startpos,
T_INT4 numchars
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutFindSubString T_PROTO((
register T_STR t,
register T_STR s
));
T_UT_API void T_ENTRY T_EXPORT TutDumpString T_PROTO((
FILE * file,
T_STR str
));
T_UT_API T_STR T_ENTRY T_EXPORT TutDumpStringToString T_PROTO((
T_STR dest_str_return,
T_STR str
));
T_UT_API void T_ENTRY T_EXPORT TutReadString T_PROTO((
FILE * file,
T_STR str
));
T_UT_API T_STR T_ENTRY T_EXPORT TutReadStringPtr T_PROTO((
FILE * file
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStrStartsWith T_PROTO((
T_STR str,
T_STR pat
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStriStartsWith T_PROTO((
T_STR str,
T_STR pat
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStrEndsWith T_PROTO((
T_STR str,
T_STR pat
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStriEndsWith T_PROTO((
T_STR str,
T_STR pat
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutStrCat T_PROTO((
T_STR buffer,
T_INT4 buffer_size,
...
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStrTok T_PROTO((
T_STR cp,
T_STR * nxt
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStringToRealInvalid T_PROTO((
T_STR input_str
));
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutStringToUnsignedReal T_PROTO((
T_STR input_str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStringToIntInvalid T_PROTO((
T_STR input_str
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutStringToInt T_PROTO((
T_STR input_str
));
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutStringToSignedReal T_PROTO((
T_STR input_str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStrToIdFileName T_PROTO((
T_STR str_in_out
));
T_UT_API T_STR * T_ENTRY T_EXPORT TutStrListDup T_PROTO((
T_STR * str_list,
T_INT4 num_str_list
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStrListEquali T_PROTO((
T_STR * str_list1,
T_INT4 num_str_list1,
T_STR * str_list2,
T_INT4 num_str_list2
));

/* time.c */
T_UT_API T_STR T_ENTRY T_EXPORT TutGetWallTimeStr T_PROTO((void));
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutGetCurrentTime T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetCurrentTimeStruct T_PROTO((
T_TIME timep
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetCurrentTime T_PROTO((
T_REAL8 current_time
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetCurrentTimeStruct T_PROTO((
T_TIME timep
));
T_UT_API T_CB T_ENTRY T_EXPORT TutTimeChangeCbCreate T_PROTO((
T_TIME_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutTimeChangeCbLookup T_PROTO((
T_TIME_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutGetWallTime T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetWallTimeStruct T_PROTO((
T_TIME_STRUCT * time_return
));
T_UT_API void T_ENTRY T_EXPORT TutSetTestWallTimeStruct T_PROTO((
T_TIME wall_time
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutTimeRatio T_PROTO((
T_TIME t1,
T_TIME t2
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTimeMultInt T_PROTO((
T_TIME tr,
T_TIME timep,
T_INT4 n
));

/* timecvt.c */
T_UT_API T_TIME_CVT T_ENTRY T_EXPORT TutTimeCvtCreate T_PROTO((
T_STR name,
T_TIME_CVT_NUM_TO_STR_FUNC num_to_str_func,
T_TIME_CVT_STR_TO_NUM_FUNC str_to_num_func,
T_TIME_CVT_DESTROY_FUNC destroy_func
));
T_UT_API T_TIME_CVT T_ENTRY T_EXPORT TutTimeCvtLookup T_PROTO((
T_STR name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTimeCvtDestroy T_PROTO((
T_TIME_CVT time_cvtr
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutTimeCvtTraverse T_PROTO((
T_TIME_CVT_TRAV_FUNC func,
T_PTR arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTimeCvtNumToStr T_PROTO((
T_TIME_CVT time_cvtr_ptr,
T_REAL8 time_num,
T_STR * time_str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTimeCvtStrToNum T_PROTO((
T_TIME_CVT time_cvtr_ptr,
T_STR time_str,
T_REAL8 * time_num_return
));
T_UT_API void T_ENTRY T_EXPORT TutTimeCvtSetCurrent T_PROTO((
T_TIME_CVT time_cvtr_ptr
));
T_UT_API T_STR T_ENTRY T_EXPORT TutTimeNumToStr T_PROTO((
T_REAL8 time_num
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTimeStrToNum T_PROTO((
T_STR time_str,
T_REAL8 * time_num_return
));
T_UT_API T_STR T_ENTRY T_EXPORT TutTimeToString T_PROTO((
T_REAL8 time_num,
T_STR time_str_return
));

/* utframe.c */
T_UT_API T_INT4 * T_ENTRY T_EXPORT TutFrameCountGetPtr T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutFrameCheck T_PROTO((
T_BOOL sleep_flag
));
T_UT_API void T_ENTRY T_EXPORT TutFrameReset T_PROTO((void));

/* util.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutInitThreads T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutProcessMutexLock T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutProcessMutexUnlock T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutResourceLock T_PROTO((
T_PTR resource
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutResourceUnlock T_PROTO((
T_PTR resource
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutGetCurrentSbrk T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutProductInit T_PROTO((
T_STR product_name,
T_STR product_key
));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetProductName T_PROTO((void));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetProductKey T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutInit T_PROTO((
T_STR process_type
));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetProcessType T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutGetCpuTime T_PROTO((void));
T_UT_API T_STR T_ENTRY T_EXPORT TutTypeToString T_PROTO((
T_TYPE type,
T_STR ret_str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStringToType T_PROTO((
T_TYPE * type_return,
T_STR type_string
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicenseToString T_PROTO((
T_LICENSE type,
T_STR * type_str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStringToBool T_PROTO((
T_BOOL * value_return,
T_STR type_string
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStringToId T_PROTO((
T_STR input_str
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutGetNUserName T_PROTO((
T_STR buffer,
T_INT4 buffer_size
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutGetNNodeName T_PROTO((
T_STR buffer,
T_INT4 buffer_size
));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetUserName T_PROTO((
T_STR name_return
));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetNodeName T_PROTO((
T_STR name_return
));
T_UT_API void T_ENTRY T_EXPORT TutStringCopy T_PROTO((
T_STR * string_ptr,
T_STR string_value
));
T_UT_API void T_ENTRY T_EXPORT TutAssert T_PROTO((
T_BOOL expr,
T_STR expr_str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API void T_ENTRY T_EXPORT TutExpect T_PROTO((
T_BOOL expr,
T_STR expr_str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutGetStackTrace T_PROTO((
T_PTR traces[],
T_INT4 max_traces
));
T_UT_API T_STR T_ENTRY T_EXPORT TutStackTraceResolveSymbol T_PROTO((
T_PTR trace
));
T_UT_API void T_ENTRY T_EXPORT TutPrintStackTrace T_PROTO((
T_PTR *traces,
T_INT4 num_traces,
T_OUT_FUNC out_func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutStackTrace T_PROTO((
T_OUT_FUNC out_func,
T_CSTR format_str,
...
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetFatalErrorFile T_PROTO((
FILE ** file_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetFatalErrorFile T_PROTO((
FILE * file
));
T_UT_API void T_ENTRY_VA T_EXPORT TutFatalError T_PROTO((
T_CONST T_STR format_str,
...
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutRandom T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutRandomSeed T_PROTO((
T_INT4 seed
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetSupportNotice T_PROTO((
T_SAFE_STR_STRUCT * safestr
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutAtExit T_PROTO((
T_AT_EXIT_FUNC func
));
T_UT_API void T_ENTRY T_EXPORT TutFlushStdout T_PROTO((void));
T_UT_API T_PTR T_ENTRY T_EXPORT TutGetPageSize T_PROTO((void));
T_UT_API T_PTR T_ENTRY T_EXPORT TutGetInitialSbrk T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutSetInitialSbrk T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutRedirect T_PROTO((
T_INT4 * ac,
T_CHAR *** av
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutIdIsValid T_PROTO((
T_STR name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSlotIsValid T_PROTO((
T_STR name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCreateGuid T_PROTO((
T_GUID_PTR guid_return
));
T_UT_API T_STR T_ENTRY T_EXPORT TutGuidToGuidStr T_PROTO((
T_GUID_PTR guid_ptr,
T_STR guid_str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGuidStrToGuid T_PROTO((
T_STR guid_str,
T_GUID_PTR guid_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDestroyGuid T_PROTO((
T_GUID_PTR guid
));
T_UT_API void T_ENTRY T_EXPORT TutExit T_PROTO((
T_INT4 status
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPasswordStrEncode T_PROTO((
T_STR str_to_encode,
T_UINT1 encoded_buf[20]
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPasswordCheck T_PROTO((
T_STR str_to_check,
T_UINT1 encoded_buf_to_check[20]
));
T_UT_API T_ENCRYPT_KEY T_ENTRY T_EXPORT TutKeyCreate T_PROTO((
T_PTR key,
T_INT4 key_size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutKeyDestroy T_PROTO((
T_ENCRYPT_KEY encrypt_key
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutKeyCompare T_PROTO((
T_ENCRYPT_KEY encrypt_key1,
T_ENCRYPT_KEY encrypt_key2
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutNoSupport T_PROTO((
T_STR filename,
T_STR funcname,
T_STR funcparm,
T_INT4 retval
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutGetPidGuardian T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutBinaryToUrlEncodedStr T_PROTO((
T_UINT1 * buffer,
T_INT4 buffer_len,
T_STR encoded_buffer,
T_INT4 encoded_buffer_size
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutStrToUrlEncodedStr T_PROTO((
T_STR str,
T_STR encoded_buffer,
T_INT4 encoded_buffer_size
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutUrlEncodedStrToStr T_PROTO((
T_STR url_encoded,
T_STR buffer,
T_INT4 buffer_size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetIdentStr T_PROTO((
T_STR * type_str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetIdentStr T_PROTO((
T_STR type_str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetIdentStrFromLicense T_PROTO((
T_LICENSE license
));
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutGetStartTime T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutSetStartTime T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGetenv T_PROTO((
T_STR name,
T_STR * value_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPutenv T_PROTO((
T_STR name_and_value
));

/* utgraph.c */
T_UT_API T_CB T_ENTRY T_EXPORT TutGraphChangeCbCreate T_PROTO((
T_GRAPH graph,
T_GRAPH_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_CB T_ENTRY T_EXPORT TutGraphChangeCbLookup T_PROTO((
T_GRAPH graph,
T_GRAPH_CHANGE_CB_FUNC func,
T_CB_ARG arg
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphSetWeightedEdges T_PROTO((
T_GRAPH graph,
T_BOOL weighted_edges
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphGetWeightedEdges T_PROTO((
T_GRAPH graph,
T_BOOL * return_weighted_edges
));
T_UT_API T_GRAPH T_ENTRY T_EXPORT TutGraphCreate T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphDestroy T_PROTO((
T_GRAPH graph
));
T_UT_API T_GRAPH_EDGE T_ENTRY T_EXPORT TutGraphEdgeAdd T_PROTO((
T_GRAPH graph,
T_GRAPH_VERTEX tail_vertex,
T_GRAPH_VERTEX head_vertex,
T_PTR edge_id,
T_INT4 weight
));
T_UT_API T_GRAPH_EDGE T_ENTRY T_EXPORT TutGraphEdgeUndirectedAdd T_PROTO((
T_GRAPH graph,
T_GRAPH_VERTEX vertex1,
T_GRAPH_VERTEX vertex2,
T_PTR edge_id1,
T_PTR edge_id2,
T_INT4 weight
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphEdgeUndirectedRemove T_PROTO((
T_GRAPH graph,
T_GRAPH_EDGE edge
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphEdgeRemove T_PROTO((
T_GRAPH graph,
T_GRAPH_EDGE edge
));
T_UT_API T_GRAPH_VERTEX T_ENTRY T_EXPORT TutGraphVertexAdd T_PROTO((
T_GRAPH graph,
T_PTR vertex_id
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphVertexRemove T_PROTO((
T_GRAPH graph,
T_GRAPH_VERTEX vertex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphSetShortPath T_PROTO((
T_GRAPH graph,
T_GRAPH_VERTEX origin_vertex
));
T_UT_API T_GRAPH_VERTEX T_ENTRY T_EXPORT TutGraphGetFirstHopVertex T_PROTO((
T_GRAPH graph,
T_GRAPH_VERTEX destination_vertex
));
T_UT_API T_GRAPH_VERTEX T_ENTRY T_EXPORT TutGraphVertexGetFirst T_PROTO((
T_GRAPH graph
));
T_UT_API T_GRAPH_VERTEX T_ENTRY T_EXPORT TutGraphVertexGetNext T_PROTO((
T_GRAPH_VERTEX vertex
));
T_UT_API T_GRAPH_VERTEX T_ENTRY T_EXPORT TutGraphVertexLookup T_PROTO((
T_GRAPH graph,
T_PTR vertex_id
));
T_UT_API T_GRAPH_EDGE T_ENTRY T_EXPORT TutGraphEdgeGetFirst T_PROTO((
T_GRAPH_VERTEX vertex
));
T_UT_API T_GRAPH_EDGE T_ENTRY T_EXPORT TutGraphEdgeGetNext T_PROTO((
T_GRAPH_EDGE edge
));
T_UT_API T_GRAPH_EDGE T_ENTRY T_EXPORT TutGraphEdgeLookup T_PROTO((
T_GRAPH graph,
T_GRAPH_VERTEX vertex1,
T_GRAPH_VERTEX vertex2
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutGraphDump T_PROTO((
T_GRAPH graph,
T_OUT_FUNC out_func
));

/* utsocket.c */
T_UT_API T_STR T_ENTRY T_EXPORT TutGetSocketDir T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketParseIpAddr T_PROTO((
T_STR node_name,
T_UINT4 * ip_addr_return
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutSocketRecvTimeout T_PROTO((
T_SOCK socket_fd,
T_PTR buf,
T_INT4 size,
T_INT4 flags,
T_REAL8 timeout,
T_BOOL * timeout_reached_return
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutSocketRecvAll T_PROTO((
T_SOCK socket_fd,
T_PTR buf,
T_INT4 size,
T_INT4 flags
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSleep T_PROTO((
T_REAL8 amount
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketCreateServerLocal T_PROTO((
T_STR file_name
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketConnectBeginLocal T_PROTO((
T_STR file_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketConnectCompleteLocal T_PROTO((
T_SOCK socket_fd
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketCreateClientLocal T_PROTO((
T_STR file_name
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketCreateServerTcp T_PROTO((
T_INT4 port
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketCreateServerTcpEx T_PROTO((
T_STR node_name,
T_INT4 port
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketConnectBeginTcp T_PROTO((
T_STR node_name,
T_INT4 port,
T_BOOL blocking
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketConnectCompleteTcp T_PROTO((
T_SOCK socket_fd,
T_REAL8 timeout
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketCreateClientTcp T_PROTO((
T_STR node_name,
T_INT4 port
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketCreateServerBcast T_PROTO((
T_INT4 port
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketCreateClientBcast T_PROTO((
T_STR node_name,
T_INT4 port,
struct sockaddr_in * bcast_addr_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketCheck T_PROTO((
T_SOCK socket_fd,
T_IO_CHECK_MODE check_mode,
T_REAL8 timeout
));
T_UT_API T_SOCK T_ENTRY T_EXPORT TutSocketAccept T_PROTO((
T_SOCK socket_fd
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketGetBlockMode T_PROTO((
T_SOCK socket_fd,
T_BOOL * block_mode_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketSetBlockMode T_PROTO((
T_SOCK socket_fd,
T_BOOL block_mode
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketGetRecvBufSize T_PROTO((
T_SOCK socket_fd,
T_INT4 * recv_buf_size_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketSetRecvBufSize T_PROTO((
T_SOCK socket_fd,
T_INT4 recv_buf_size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketGetSendBufSize T_PROTO((
T_SOCK socket_fd,
T_INT4 * send_buf_size_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketSetSendBufSize T_PROTO((
T_SOCK socket_fd,
T_INT4 send_buf_size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompareNodeNames T_PROTO((
T_STR name1,
T_STR name2,
T_BOOL * compare_result
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutSocketGetNNameStr T_PROTO((
T_SOCK socket_fd,
T_BOOL include_port,
T_STR buffer,
T_INT4 buffer_size
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutSocketGetNPeerNameStr T_PROTO((
T_SOCK socket_fd,
T_BOOL include_port,
T_STR buffer,
T_INT4 buffer_size
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketGetNameStr T_PROTO((
T_SOCK socket_fd,
T_BOOL include_port,
T_STR name_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketGetPeerNameStr T_PROTO((
T_SOCK socket_fd,
T_BOOL include_port,
T_STR name_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSocketGetPort T_PROTO((
T_SOCK socket_fd,
T_INT4 * port_return
));

/* utsystem.c */
T_UT_API T_INT4 T_ENTRY T_EXPORT TutSystem T_PROTO((
T_STR command
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSystemTimeout T_PROTO((
T_STR command,
T_REAL8 timeout,
T_BOOL stop_flag,
T_INT4 * status_return
));

/* utthread.c */
T_UT_API T_UTLIB_TSD T_ENTRY T_EXPORT TutGetLibTsdValue T_PROTO((void));
T_UT_API T_COND T_ENTRY T_EXPORT TutCondAttachNamedNp T_PROTO((
T_STR name
));
T_UT_API T_COND T_ENTRY T_EXPORT TutCondCreateNamedNp T_PROTO((
T_STR name
));
T_UT_API T_COND T_ENTRY T_EXPORT TutCondCreate T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCondDestroy T_PROTO((
T_COND cond
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCondWakeAll T_PROTO((
T_COND cond
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCondWait T_PROTO((
T_COND cond,
T_MUTEX mutex,
T_REAL8 timeout
));
T_UT_API T_MUTEX T_ENTRY T_EXPORT TutMutexAttachNamedNp T_PROTO((
T_STR name
));
T_UT_API T_MUTEX T_ENTRY T_EXPORT TutMutexCreateNamedNp T_PROTO((
T_STR name,
T_BOOL initial_state
));
T_UT_API T_MUTEX T_ENTRY T_EXPORT TutMutexCreateFast T_PROTO((
T_BOOL initial_state
));
T_UT_API T_MUTEX T_ENTRY T_EXPORT TutMutexCreate T_PROTO((
T_BOOL initial_state
));
T_UT_API T_MUTEX T_ENTRY T_EXPORT TutMutexCreateEx T_PROTO((
T_BOOL initial_state
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutMutexDestroy T_PROTO((
T_MUTEX mutex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutMutexLock T_PROTO((
T_MUTEX mutex,
T_REAL8 timeout
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutMutexUnlock T_PROTO((
T_MUTEX mutex
));
T_UT_API T_RW_MUTEX T_ENTRY T_EXPORT TutRwMutexCreate T_PROTO((
T_BOOL initial_state,
T_INT4 read_quota
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexDestroy T_PROTO((
T_RW_MUTEX rw_mutex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexGetReadQuota T_PROTO((
T_RW_MUTEX rw_mutex,
T_INT4 * read_quota_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexSetReadQuota T_PROTO((
T_RW_MUTEX rw_mutex,
T_INT4 read_quota
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexReadLock T_PROTO((
T_RW_MUTEX rw_mutex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexReadLocked T_PROTO((
T_RW_MUTEX rw_mutex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexWriteLock T_PROTO((
T_RW_MUTEX rw_mutex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexWriteLocked T_PROTO((
T_RW_MUTEX rw_mutex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexUnlock T_PROTO((
T_RW_MUTEX rw_mutex
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutRwMutexUpgradeLock T_PROTO((
T_RW_MUTEX rw_mutex,
T_REAL8 timeout
));
T_UT_API T_SPINLOCK T_ENTRY T_EXPORT TutSpinlockCreate T_PROTO((
T_INT4 initial_state
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSpinlockLock T_PROTO((
T_SPINLOCK sl
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSpinlockUnlock T_PROTO((
T_SPINLOCK sl
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSpinlockDestroy T_PROTO((
T_SPINLOCK sl
));
T_UT_API T_THREAD T_ENTRY T_EXPORT TutThreadPosixGetInvalid T_PROTO((void));
T_UT_API T_THREAD T_ENTRY_VA T_EXPORT TutThreadCreate T_PROTO((
T_THREAD_FUNC thread_func,
T_PTR thread_arg,
...
));
T_UT_API T_THREAD T_ENTRY_VA T_EXPORT TutThreadCreateVa T_PROTO((
T_THREAD_FUNC thread_func,
T_PTR thread_arg,
va_list var_arg_list
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutThreadEqual T_PROTO((
T_THREAD t1,
T_THREAD t2
));
T_UT_API void T_ENTRY T_EXPORT TutThreadExit T_PROTO((
T_PTR exit_code
));
T_UT_API T_THREAD T_ENTRY T_EXPORT TutThreadSelf T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutThreadWait T_PROTO((
T_THREAD thread,
T_PTR * exit_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutThreadDetach T_PROTO((
T_THREAD thread
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTsdKeyCreate T_PROTO((
T_TSD_KEY * key_return,
T_TSD_KEY_DESTRUCTOR_FUNC destructor_func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTsdKeyDestroy T_PROTO((
T_TSD_KEY key
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTsdGetValue T_PROTO((
T_TSD_KEY key,
T_PTR * value_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTsdSetValue T_PROTO((
T_TSD_KEY key,
T_PTR value
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutEndImportThreadCheckerThread T_PROTO((void));

/* utalloc.c */
T_UT_API T_PTR T_ENTRY T_EXPORT TutTryMalloc T_PROTO((
T_UNINT size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutTryCalloc T_PROTO((
T_UNINT size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutTryRealloc T_PROTO((
T_PTR ptr,
T_UNINT size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutMalloc T_PROTO((
T_UINT4 size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutCalloc T_PROTO((
T_UINT4 size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutRealloc T_PROTO((
T_PTR ptr,
T_UINT4 size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutNMalloc T_PROTO((
T_UNINT size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutNCalloc T_PROTO((
T_UNINT size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutNRealloc T_PROTO((
T_PTR ptr,
T_UNINT size
));
T_UT_API void T_ENTRY T_EXPORT TutFree T_PROTO((
T_PTR ptr
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutMallocCheck T_PROTO((
T_UINT4 size,
T_STR var_str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutCallocCheck T_PROTO((
T_UINT4 size,
T_STR var_str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutReallocCheck T_PROTO((
T_PTR var,
T_UINT4 size,
T_STR var_str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutNMallocCheck T_PROTO((
T_UNINT size,
T_STR str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutNCallocCheck T_PROTO((
T_UNINT size,
T_STR str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutNReallocCheck T_PROTO((
T_PTR ptr,
T_UNINT size,
T_STR str,
T_STR file_name,
T_INT4 line_num
));
T_UT_API void T_ENTRY T_EXPORT TutFreeCheck T_PROTO((
T_PTR var,
T_STR var_str,
T_STR file_name,
T_INT4 line_num
));

/* utbuffer.c */
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutBufGetResizeFactor T_PROTO((void));
T_UT_API T_BUF T_ENTRY T_EXPORT TutBufCreate T_PROTO((
T_INT4 init_max
));
T_UT_API T_BUF T_ENTRY T_EXPORT TutBufCreateStatic T_PROTO((
T_PTR storage,
T_INT4 init_max
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBufDestroy T_PROTO((
T_BUF buf
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBufGrow T_PROTO((
T_BUF buf,
T_INT4 desired_max
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutBufAllocAligned T_PROTO((
T_BUF buf,
T_INT4 size,
T_INT4 align
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutBufAppendBuf T_PROTO((
T_BUF dst_buf,
T_BUF src_buf,
T_INT4 size
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutBufAppendRange T_PROTO((
T_BUF dst_buf,
T_BUF src_buf,
T_INT4 begin,
T_INT4 end
));
T_UT_API T_BUF T_ENTRY T_EXPORT TutBufCloneRange T_PROTO((
T_BUF src_buf,
T_INT4 begin,
T_INT4 end
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBufDeleteRange T_PROTO((
T_BUF buf,
T_INT4 begin,
T_INT4 end
));
T_UT_API T_PTR T_ENTRY T_EXPORT TutBufNextAligned T_PROTO((
T_BUF buf,
T_INT4 size,
T_INT4 align
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBufReset T_PROTO((
T_BUF buf,
T_PTR ptr
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBufRewind T_PROTO((
T_BUF buf,
T_PTR ptr
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBufGetSize T_PROTO((
T_BUF buf,
T_INT4 * size_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBufSetSize T_PROTO((
T_BUF buf,
T_INT4 new_size
));

/* utcat.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFlagSet T_PROTO((
T_CAT cat,
T_UINT4 flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFlagClear T_PROTO((
T_CAT cat,
T_UINT4 flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatSeverityStrToVal T_PROTO((
T_CHAR val,
T_CAT_SEVERITY * severity
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFileLoad T_PROTO((
T_CATF catf
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatLookup T_PROTO((
T_CAT cat,
T_INT4 msg_id,
T_CAT_HASH_MSG * msgptr_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatGetDisplayStr T_PROTO((
T_CAT cat,
T_CAT_HASH_MSG msg_ptr,
T_STR * str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatGetStr T_PROTO((
T_CAT cat,
T_INT4 msg_id,
T_STR * str_return
));
T_UT_API T_CAT T_ENTRY T_EXPORT TutCatCreate T_PROTO((
T_STR fname
));
T_UT_API void T_ENTRY T_EXPORT TutCatAddref T_PROTO((
T_CAT cat
));
T_UT_API void T_ENTRY T_EXPORT TutCatRelease T_PROTO((
T_CAT cat
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatDestroy T_PROTO((
T_CAT cat
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFilenameOptionBind T_PROTO((
T_CAT cat,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFlagsOptionBind T_PROTO((
T_CAT cat,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFilenameOptionUnbind T_PROTO((
T_CAT cat,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFlagsOptionUnbind T_PROTO((
T_CAT cat,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFilenameSet T_PROTO((
T_CAT cat,
T_STR fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFilenameGet T_PROTO((
T_CAT cat,
T_STR * filename
));
T_UT_API T_CATF T_ENTRY T_EXPORT TutCatFileCreate T_PROTO((
T_STR fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCatFileDestroy T_PROTO((
T_CATF cat_file
));

/* utcompr.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompressorInit T_PROTO((
T_STR name,
T_COMPRESSOR_CREATE_FUNC create_func,
T_COMPRESSOR_COMPRESS_FUNC compress_func,
T_COMPRESSOR_UNCOMPRESS_FUNC uncompress_func,
T_COMPRESSOR_GET_STATS_FUNC get_stats_func,
T_COMPRESSOR_RESET_FUNC reset_func,
T_COMPRESSOR_DESTROY_FUNC destroy_func
));
T_UT_API T_COMPRESSOR T_ENTRY T_EXPORT TutCompressorCreate T_PROTO((
T_STR name,
T_STR args
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompressorCompress T_PROTO((
T_COMPRESSOR comp,
T_BUF dest,
T_BUF src,
T_COMPRESSOR_FLUSH flush
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompressorUncompress T_PROTO((
T_COMPRESSOR comp,
T_BUF dest,
T_BUF src,
T_COMPRESSOR_FLUSH flush
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompressorGetStats T_PROTO((
T_COMPRESSOR comp,
T_COMPRESSOR_STATS stats_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompressorSetIdent T_PROTO((
T_COMPRESSOR comp,
T_STR ident_str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompressorReset T_PROTO((
T_COMPRESSOR comp
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompressorDestroy T_PROTO((
T_COMPRESSOR comp
));
T_UT_API T_BOOL T_ENTRY T_EXPORT utCompressorPoolInit T_PROTO((void));
T_UT_API T_COMPRESSOR T_ENTRY T_EXPORT utCompressorPoolGet T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT utCompressorPoolPut T_PROTO((
T_COMPRESSOR comp
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutCompress T_PROTO((
T_BUF dest,
T_BUF src
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutUncompress T_PROTO((
T_BUF dest,
T_BUF src
));

/* utout.c */
T_UT_API void T_ENTRY_VA T_EXPORT TutOut T_PROTO((
T_STR format_str,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutOutFlush T_PROTO((
T_STR format_str,
...
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutSetOutFlushFunc T_PROTO((
T_OUT_VA_FLUSH_FUNC flush_func
));
T_UT_API T_OUT_VA_FLUSH_FUNC T_ENTRY T_EXPORT TutGetOutFlushFunc T_PROTO((void));
T_UT_API void T_ENTRY_VA T_EXPORT TutVerbose T_PROTO((
T_STR format_str,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutOutDebug T_PROTO((
T_STR format_str,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutVOut T_PROTO((
T_STR format_str,
va_list var_arg_ptr
));
T_UT_API void T_ENTRY T_EXPORT TutSetOutputFunc T_PROTO((
T_OUT_VA_FUNC output_func
));
T_UT_API T_OUT_VA_FUNC T_ENTRY T_EXPORT TutGetOutputFunc T_PROTO((void));
T_UT_API void T_ENTRY_VA T_EXPORT TutVDebug T_PROTO((
T_STR format_str,
va_list var_arg_ptr
));
T_UT_API void T_ENTRY_VA T_EXPORT TutDebug T_PROTO((
T_STR format_str,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutWarning T_PROTO((
T_STR format_str,
...
));
T_UT_API void T_ENTRY T_EXPORT TutDebugOpen T_PROTO((
T_STR file_name
));
T_UT_API void T_ENTRY T_EXPORT TutDebugClose T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutDebugReopen T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDebugRename T_PROTO((
T_STR file_name
));
T_UT_API T_STR T_ENTRY T_EXPORT TutDebugFileName T_PROTO((void));
T_UT_API FILE * T_ENTRY T_EXPORT TutDebugFilePtr T_PROTO((void));
T_UT_API FILE * T_ENTRY T_EXPORT TutDumpOpen T_PROTO((void));
T_UT_API FILE * T_ENTRY T_EXPORT TutDumpOpenAppend T_PROTO((void));
T_UT_API void T_ENTRY_VA T_EXPORT TutDumpOutVa T_PROTO((
T_STR format_str,
va_list var_arg_ptr
));
T_UT_API void T_ENTRY_VA T_EXPORT TutDumpOut T_PROTO((
T_STR format_str,
...
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDumpClose T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDumpView T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDumpRemove T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDumpGetName T_PROTO((
T_STR * fname_return
));
T_UT_API void T_ENTRY T_EXPORT TutOutInit T_PROTO((void));
T_UT_API void T_ENTRY T_EXPORT TutOutCat T_PROTO((
T_UT_TRACE_LEVEL level,
T_INT4 msg_id,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutVOutStr T_PROTO((
T_UT_TRACE_LEVEL level,
T_STR format_str,
va_list var_arg_ptr
));
T_UT_API void T_ENTRY T_EXPORT TutOutStr T_PROTO((
T_UT_TRACE_LEVEL level,
T_STR format_str,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutVOutStrDefault T_PROTO((
T_STR format_str,
va_list var_arg_ptr
));
T_UT_API void T_ENTRY_VA T_EXPORT TutOutStrDefault T_PROTO((
T_STR format_str,
...
));

/* utproc.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutProcInfo T_PROTO((
T_PRINFO_TYPE request,
T_PTR data
));

/* uttrace.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceLevelStrToVal T_PROTO((
T_STR str,
T_UT_TRACE_LEVEL * trace_level
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceLevelValToStr T_PROTO((
T_UT_TRACE_LEVEL trace_level,
T_STR * str
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceLevelOptionBind T_PROTO((
T_UT_TRACE trace,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceLevelOptionUnbind T_PROTO((
T_UT_TRACE trace,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceCatalogUnbind T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFileOptionBind T_PROTO((
T_UT_TRACE trace,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFileOptionUnbind T_PROTO((
T_UT_TRACE trace,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFlagsOptionBind T_PROTO((
T_UT_TRACE trace,
T_STR option_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFlagsOptionUnbind T_PROTO((
T_UT_TRACE trace,
T_STR option_name
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceLevelOptionCreate T_PROTO((
T_STR option_name
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceFileOptionCreate T_PROTO((
T_STR option_name
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceFlagsOptionCreate T_PROTO((
T_STR option_name
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceLevelDefaultOptionCreate T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceLevelDefaultOptionLookup T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceLevelDefaultOptionDestroy T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceFileDefaultOptionCreate T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceFileDefaultOptionLookup T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFileDefaultOptionDestroy T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceFlagsDefaultOptionCreate T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_OPTION T_ENTRY T_EXPORT TutTraceFlagsDefaultOptionLookup T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFlagsDefaultOptionDestroy T_PROTO((
T_UT_TRACE trace
));
T_UT_API T_UT_TRACE T_ENTRY T_EXPORT TutTraceCreate T_PROTO((
T_STR name,
T_STR fname,
T_UINT4 flags,
T_STR prefix
));
T_UT_API T_UT_TRACE T_ENTRY T_EXPORT TutTraceCreateWithCatalog T_PROTO((
T_STR name,
T_STR fname,
T_UINT4 flags,
T_STR prefix
));
T_UT_API void T_ENTRY T_EXPORT TutTraceAddref T_PROTO((
T_UT_TRACE trace
));
T_UT_API void T_ENTRY T_EXPORT TutTraceRelease T_PROTO((
T_UT_TRACE * trace
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceDestroy T_PROTO((
T_UT_TRACE * trace
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFileSet T_PROTO((
T_UT_TRACE trace,
T_STR fname
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceLevelSet T_PROTO((
T_UT_TRACE trace,
T_UT_TRACE_LEVEL level
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceLevelGet T_PROTO((
T_UT_TRACE trace,
T_UT_TRACE_LEVEL * level
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFlagSet T_PROTO((
T_UT_TRACE trace,
T_UINT4 flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceFlagClear T_PROTO((
T_UT_TRACE trace,
T_UINT4 flag
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTracePrefixSet T_PROTO((
T_UT_TRACE trace,
T_STR prefix
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTracePrefixGet T_PROTO((
T_UT_TRACE trace,
T_STR * prefix
));
T_UT_API void T_ENTRY_VA T_EXPORT TutTraceVa T_PROTO((
T_UT_TRACE trace,
T_UT_TRACE_LEVEL level,
T_STR format_str,
va_list var_arg_ptr
));
T_UT_API void T_ENTRY T_EXPORT TutTraceMapSeverityToTraceLevel T_PROTO((
T_CAT_SEVERITY severity,
T_UT_TRACE_LEVEL * level
));
T_UT_API void T_ENTRY_VA T_EXPORT TutTraceCatVa T_PROTO((
T_UT_TRACE trace,
T_UT_TRACE_LEVEL level,
T_INT4 msg_id,
va_list var_arg_ptr
));
T_UT_API void T_ENTRY_VA T_EXPORT TutTraceCat T_PROTO((
T_UT_TRACE trace,
T_UT_TRACE_LEVEL level,
T_INT4 msg_id,
...
));
T_UT_API void T_ENTRY_VA T_EXPORT TutTrace T_PROTO((
T_UT_TRACE trace,
T_UT_TRACE_LEVEL level,
T_STR format_str,
...
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutTraceCatalogBind T_PROTO((
T_CAT cat,
T_UT_TRACE trace
));

/* utlic.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicFileDump T_PROTO((
T_OUT_FUNC out_func
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicReadFromFile T_PROTO((
T_LICENSE_PRODUCTS product,
T_STR * license_str_in_out
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicProductToStr T_PROTO((
T_LICENSE_PRODUCTS product,
T_STR * product_str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicStrToProduct T_PROTO((
T_STR product_str,
T_LICENSE_PRODUCTS * product_return
));
T_UT_API void T_ENTRY T_EXPORT TutLicGetMarkerStr T_PROTO((
T_STR marker_return
));
T_UT_API void T_ENTRY T_EXPORT TutLicGetSerialNumberStr T_PROTO((
T_SERIAL_NUMBER_DATA sn,
T_SERIAL_NUMBER_STR result
));
T_UT_API T_INT2 T_ENTRY T_EXPORT TutLicCalcCustomerChecksum T_PROTO((
T_STR cust_id
));
T_UT_API T_SERIAL_NUMBER_CELL T_ENTRY T_EXPORT TutLicCalcExternalSerialNumberChecksum T_PROTO((
T_SERIAL_NUMBER_DATA sn
));
T_UT_API T_SERIAL_NUMBER_CELL T_ENTRY T_EXPORT TutLicCalcInternalSerialNumberChecksum T_PROTO((
T_SERIAL_NUMBER_DATA sn
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicDecodeSerialNumber T_PROTO((
T_SERIAL_NUMBER_DATA serial_number
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicEncodeSerialNumber T_PROTO((
T_STR serial_number,
T_INT4 encoding
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicDecomposeSerialNumber T_PROTO((
T_STR sn,
T_LICENSE_DATA plicense
));
T_UT_API T_LICENSE_DATA T_ENTRY T_EXPORT TutLicDataCreate T_PROTO((
T_STR license
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLicDataGetServerCount T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLicDataGetClientCount T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLicDataGetSiteId T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_LICENSE_PRODUCTS T_ENTRY T_EXPORT TutLicDataGetProductType T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutLicDataGetProductVersion T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_REAL8 T_ENTRY T_EXPORT TutLicDataGetReferenceDate T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_STR T_ENTRY T_EXPORT TutLicDataGetCustomerId T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_UINT4 T_ENTRY T_EXPORT TutLicDataGetCapabilities T_PROTO((
T_LICENSE_DATA plicense
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLicDataDump T_PROTO((
T_LICENSE_DATA plicense,
T_OUT_FUNC out_func
));

/* utprops.c */
T_UT_API T_PROPERTIES T_ENTRY T_EXPORT TutPropertiesCreate T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPropertiesSet T_PROTO((
T_PROPERTIES props,
T_STR name,
T_STR value
));
T_UT_API T_STR T_ENTRY T_EXPORT TutPropertiesTraverse T_PROTO((
T_PROPERTIES props,
T_PROPERTY_TRAV_FUNC func,
T_PTR arg
));
T_UT_API T_STR T_ENTRY T_EXPORT TutPropertiesGet T_PROTO((
T_PROPERTIES props,
T_STR name
));
T_UT_API T_STR T_ENTRY T_EXPORT TutPropertiesGetDefault T_PROTO((
T_PROPERTIES props,
T_STR name,
T_STR default_value
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPropertiesGetCount T_PROTO((
T_PROPERTIES props,
T_INT4 * count_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPropertiesDestroy T_PROTO((
T_PROPERTIES props
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPropertiesCopy T_PROTO((
T_PROPERTIES prop_src,
T_PROPERTIES prop_dst
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutPropertiesReset T_PROTO((
T_PROPERTIES props
));

/* loadlib.c */
T_UT_API T_LIBRARY T_ENTRY T_EXPORT TutLibraryLoad T_PROTO((
T_STR dll_name,
T_BOOL bWantDecorated
));
T_UT_API T_FUNCTION_PTR T_ENTRY T_EXPORT TutLibrarySymbolLookup T_PROTO((
T_LIBRARY handle,
T_STR symbol_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutLibraryUnLoad T_PROTO((
T_LIBRARY handle
));

/* utdaemon.c */
T_UT_API void T_ENTRY T_EXPORT TutWinScmStatusReport T_PROTO((
T_UINT4 current_state,
T_UINT4 exit_code,
T_UINT4 wait_hint
));
T_UT_API void T_ENTRY T_EXPORT TutWinScmControl T_PROTO((
DWORD opcode
));
T_UT_API void T_ENTRY T_EXPORT TutWinScmMain T_PROTO((
DWORD _argc,
T_STR * argv
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutWinScmStartup T_PROTO((
T_STR service_name,
T_STR service_display_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutWinScmInstall T_PROTO((
T_STR service_name,
T_STR service_display_name
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutWinScmUninstall T_PROTO((
T_STR service_name,
T_STR service_display_name
));
T_UT_API void T_ENTRY T_EXPORT TutDaemonInitBanner T_PROTO((
T_STR display_name,
T_BOOL version_only,
T_STR product_string
));
T_UT_API void T_ENTRY_VA T_EXPORT TutDaemonHandleSigint T_PROTO((
int dummy
));
T_UT_API void T_ENTRY_VA T_EXPORT TutDaemonHandleSigxfsz T_PROTO((
int dummy
));
T_UT_API T_BOOL T_ENTRY_VA T_EXPORT TutDaemonInit T_PROTO((
T_STR process_type,
T_STR display_name,
T_DAEMON_INFO_STRUCT * daemon_info_holder,
T_STR product_string
));
T_UT_API void T_ENTRY T_EXPORT TutDaemonMain T_PROTO((
T_INT4 argc,
T_STR * argv
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDaemonStopCheck T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDaemonStopRequest T_PROTO((void));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDaemonIsService T_PROTO((void));
T_UT_API T_STR T_ENTRY T_EXPORT TutDaemonGetUsername T_PROTO((void));
T_UT_API T_STR T_ENTRY T_EXPORT TutDaemonGetPassword T_PROTO((void));

/* utmd5.c */
T_UT_API void T_ENTRY T_EXPORT TutMD5Init T_PROTO((
T_MD5_CTX * context
));
T_UT_API void T_ENTRY T_EXPORT TutMD5Update T_PROTO((
T_MD5_CTX * context,
T_PTR input_ptr,
T_UINT4 inputLen
));
T_UT_API void T_ENTRY T_EXPORT TutMD5Final T_PROTO((
T_UCHAR digest[16],
T_MD5_CTX * context
));

/* utbase64.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBase64Decode T_PROTO((
T_STR base64_src,
T_UINT1 * buffer,
T_INT4 buffer_size,
T_INT4 * length_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutBase64Encode T_PROTO((
T_UINT1 * binary_data,
T_INT4 size,
T_STR base64_str,
T_INT4 base64_size
));

/* xml.c */
T_UT_API T_XML T_ENTRY T_EXPORT TutXmlCreate T_PROTO((
T_STR xml_str
));
T_UT_API T_XML T_ENTRY T_EXPORT TutXmlCreateStatic T_PROTO((
T_STR xml_str
));
T_UT_API T_XML T_ENTRY T_EXPORT TutXmlClone T_PROTO((
T_XML xml
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutXmlDestroy T_PROTO((
T_XML xml
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutXmlGetStr T_PROTO((
T_XML xml,
T_STR * str_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutXmlSetStr T_PROTO((
T_XML xml,
T_STR str
));

/* version.c */
T_UT_API T_STR T_ENTRY T_EXPORT TutGetVersionName T_PROTO((void));
T_UT_API T_INT4 T_ENTRY T_EXPORT TutGetVersionNumber T_PROTO((void));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetCopyrightNotice T_PROTO((void));
T_UT_API T_STR T_ENTRY T_EXPORT TutGetArch T_PROTO((void));

/* utdsmm.c */
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDSMMCreate T_PROTO((
T_HASH_CALC_FUNC hash_calc_func,
T_HASH_TEST_FUNC hash_test_func,
T_UT_DSMM_COPY_FUNC dsmm_copy_func,
T_UT_DSMM_FREE_FUNC dsmm_free_func,
T_UT_DSMM_TYPE dsmm_type,
T_UINT4 dsmm_cache_max_size,
T_UT_DSMM * dsmm_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDSMMDestroy T_PROTO((
T_UT_DSMM * dsmm
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDSMMObjectCreate T_PROTO((
T_UT_DSMM dsmm,
T_PTR key,
T_PTR * mutex_return
));
T_UT_API T_BOOL T_ENTRY T_EXPORT TutDSMMObjectDestroy T_PROTO((
T_UT_DSMM dsmm,
T_PTR key
));

/* utatomic.c */
T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicReadFast T_PROTO((
T_ATOM atom,
T_FAST_MUTEX fm
));

T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicRead T_PROTO((
T_ATOM atom,
T_MUTEX mutex
));

T_UT_API void T_ENTRY T_EXPORT TutAtomicWriteFast T_PROTO((
T_ATOM atom,
T_NINT value,
T_FAST_MUTEX fm
));

T_UT_API void T_ENTRY T_EXPORT TutAtomicWrite T_PROTO((
T_ATOM atom,
T_NINT value,
T_MUTEX mutex
));

T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicSwapFast T_PROTO((
T_ATOM atom,
T_NINT value,
T_FAST_MUTEX fm
));

T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicSwap T_PROTO((
T_ATOM atom,
T_NINT value,
T_MUTEX mutex
));

T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicCondSwapFast T_PROTO((
T_ATOM atom,
T_NINT value,
T_NINT cond_value,
T_FAST_MUTEX fm
));

T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicCondSwap T_PROTO((
T_ATOM atom,
T_NINT value,
T_NINT cond_value,
T_MUTEX mutex
));

T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicAddFast T_PROTO((
T_ATOM atom,
T_NINT value,
T_FAST_MUTEX fm
));

T_UT_API T_NINT T_ENTRY T_EXPORT TutAtomicAdd T_PROTO((
T_ATOM atom,
T_NINT value,
T_MUTEX mutex
));

T_UT_API void T_ENTRY T_EXPORT TutAtomicIncrFast T_PROTO((
T_ATOM atom,
T_FAST_MUTEX fm
));

T_UT_API void T_ENTRY T_EXPORT TutAtomicIncr T_PROTO((
T_ATOM atom,
T_MUTEX mutex
));

T_UT_API T_BOOL T_ENTRY T_EXPORT TutAtomicDecrAndTestFast T_PROTO((
T_ATOM atom,
T_FAST_MUTEX fm
));

T_UT_API T_BOOL T_ENTRY T_EXPORT TutAtomicDecrAndTest T_PROTO((
T_ATOM atom,
T_MUTEX mutex
));

#ifdef T_ASM_ATOMIC
T_UT_API void T_ENTRY_VA TutAsmAtomicMemCommit T_PROTO((void));

T_UT_API T_NINT T_ENTRY_VA TutAsmAtomicRead T_PROTO((
T_ATOM atom
));

T_UT_API T_NINT T_ENTRY_VA TutAsmAtomicWrite T_PROTO((
T_ATOM atom,
T_NINT value
));

T_UT_API T_NINT T_ENTRY_VA TutAsmAtomicAdd T_PROTO((
T_ATOM atom,
T_NINT value
));

T_UT_API T_NINT T_ENTRY_VA TutAsmAtomicSwap T_PROTO((
T_ATOM atom,
T_NINT value
));

T_UT_API void T_ENTRY_VA TutAsmAtomicInc T_PROTO((
T_ATOM atom
));

T_UT_API T_BOOL T_ENTRY_VA TutAsmAtomicDecAndTest T_PROTO((
T_ATOM atom
));
#endif

#ifdef __cplusplus
}
#endif
